= CI/CD with CircleCI
:noindex:
:page-aliases: projects:integrate-cicd-circleci.adoc[]

include::ROOT:partial$include.adoc[]

Use the `akka` orb to use CircleCI with your Akka project. The orb supports commands for installing, authenticating, and invoking the Akka CLI.

== Prerequisites

To use the `akka` orb, you'll need to:

- https://circleci.com/docs/2.0/getting-started/#setting-up-circleci[Enable CircleCI {tab-icon}, window="new"] for your source code repository containing the source code you want to deploy
- https://circleci.com/docs/2.0/build-processing/[Enable and activate pipelines{tab-icon}, window="new"] in the CircleCI project (*Project Settings -> Advanced Settings*)
- Create a xref:operations:integrate-cicd.adoc#create_a_service_token[service token] for your project
- Get the name or preferably UUID of your project, which can be obtained by running `akka projects list`

== Create an authentication context

The `akka` orb expects the authentication token and project ID as parameters. CircleCI https://circleci.com/docs/2.0/contexts/[context {tab-icon}, window="new"] allows you to store the authentication token and project ID values securely using a context.

In your CircleCI account, create a https://circleci.com/docs/2.0/contexts/[context {tab-icon}, window="new"] and:

. Store the authentication token as `AKKA_TOKEN`.
. Store the project ID as `AKKA_PROJECT`.

With the authentication variables saved, you can use them in your project configuration.

== Create a workflow

Follow these steps to create a workflow to invoke the `akka` orb for your project:

. Create a folder named `.circleci` at the root of the project folder.

. Create a file named `config.yml` in the `.circleci` folder.

. Open `config.yml` for editing and add the CircleCI version:
+
[source, yaml]
----
version: 2.1
----

. Reference the orb:
+
[source, yaml]
----
orbs:
  akka: lightbend/akka@1.0.0
----

. Add a job that creates an image and invokes orb commands. For example, to deploy a service named `my-service`:
+
[source, yaml]
----
jobs:
  run-akka:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - akka/install <1>
      - akka/exec: <2>
          cmd: services deploy my-service cimg/base:stable
----
<1> The `akka/install` command installs the Akka CLI for your CircleCI job
and configures it using the `AKKA_TOKEN` and `AKKA_PROJECT` environment
variables set in the CircleCI context.
<2> The `akka/exec` command executes any command from the Akka CLI. Do not precede commands with `akka`.

. Add a https://circleci.com/docs/2.0/workflows/[workflow {tab-icon}, window="new"] to schedule the job and give it access to the context storing the authentication variables. For example, with a refresh token and project ID stored in `akka-context`:
+
[source,yml]
----
workflows:
  version: 1
  install-and-run-akka:
    jobs:
      - run-akka
      context:
      - akka-context
----
+
By default, CircleCI jobs are triggered by any push to the repository. See the documentation for https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow[scheduling {tab-icon}, window="new"] a workflow.

. Save `.config.yml`.
