= Organizations
include::ROOT:partial$include.adoc[]

An _Organization_ in Akka is the root of the management hierarchy and serves as a container for all _Projects_ where _Services_ are deployed. It provides the context in which users operate, both in the _Akka Console_ and _Akka CLI_.

To switch between organizations, you must specify the target organization's context.

== Key Concepts

* xref:operations:manage-users.adoc[*User Membership*]: A user can belong to multiple organizations, but membership does not automatically grant access to the organization’s projects.
* xref:operations:regions.adoc[*Regions*]: Each organization has access to specific regions. Projects created within the organization are located in one or more of these regions.
* xref:operations:billing.adoc[*Billing*]: Billing is handled at the organization level, with all costs collected and paid per organization.
* xref:operations:manage-project-access.adoc[*Role-Based Access*]: Membership and project access within an organization are managed through role bindings.

== Details

* *Organization Administrator*: The first user of an organization is an Organization Administrator, who can invite or add users with different roles.
* *Project Ownership*: Each project is owned by a single organization. Users must ensure that their projects are associated with the correct organization.
* *Region Assignment*: Projects created for an organization are assigned to one or more of the organization's available regions.

== Usage

You can determine which organizations the current user is a member of using the following command:

[source,command window]
----
akka organizations list
----

Example output:
[source]
----
NAME        ID                                     ROLES
acme        1a4a9d5d-1234-5678-910a-9c8fb3700da7   superuser
----

NOTE: You can refer to the organization in `akka` commands using either the "friendly name" or the "ID" with the `--organization` flag. See the page on xref:operations:manage-users.adoc[managing organization users] to find more, including the use of organization roles.

== Topics

- xref:operations:manage-users.adoc[]
- xref:operations:regions.adoc[]
- xref:operations:billing.adoc[]
- xref:support:paid-plans.adoc[]
