
== Package and deploy your service

To build and publish the container image and then deploy the service, follow these steps:

. If you haven't done so yet, sign in to your Akka account. If this is your first time using Akka, this will let you register an account, xref:operations:projects/create-project.adoc[create your first project], and set this project as the default.
+
[source,command line]
----
akka auth login
----

. Use the `deploy` target to build the container image, publish it to the container registry as configured in the `pom.xml` file, and the target `akka:deploy` to automatically deploy the service to Akka:
+
[source,command line]
----
mvn deploy akka:deploy
----
IMPORTANT: If you time stamp your image. For example, `<dockerTag>${project.version}-${build.timestamp}</dockerTag>` you must always run both targets in one pass, i.e. `mvn deploy akka:deploy`. You cannot run `mvn deploy` first and then `mvn akka:deploy` because they will have different timestamps and thus different `dockerTag`s. This makes it impossible to reference the image in the repository from the second target.

. You can xref:operations:services/deploy-service.adoc#_verify_service_status[verify the status of the deployed service] using:
+
[source,command line]
----
akka service list
----

[#invoke]
== Invoke your service

Once the service has started successfully, you can xref:operations:services/invoke-service.adoc#_proxy_command[start a proxy locally] to access the service:

[source,command line]
----
akka service proxy <service name>
----

You can use command line HTTP clients, such as `curl` or `httpie`, to invoke the service through the proxy at `localhost:8080`, using plaintext connections.
