
== Identifying the Entity

In order to interact with an Entity in Akka, we need to assign an *type id* and one or more instance *ids*:

* *type id* is a unique identifier for all entities of a given type. To define the entity type id, the entity class must be annotated with `@ComponentId` and have a unique and stable identifier assigned.
* *id*, on the other hand, is unique per instance. In most cases, the entity id is passed as a path parameter of a REST request. The exception to the rule is when we request Akka to auto-generate a id for us. In such a case, Akka won't try to extract the id from the endpoint path.

The entity id can be defined in different ways, as detailed below.

=== Single identifier

The most common use is to annotate the class with `@Id` and assign one path variable name to it.
For instance, `@Id("id")` will instruct Akka to look up a matching path variable. For an endpoint defined with `@RequestMapping("/users/\{id}")`, Akka will extract whatever path segment is used to replace `\{id}` and treat it as the Entity unique identifier.

=== Composite identifier

It's also possible to have a composite identifier. For example, `@Id({"groupId", "id"})` defines a composite identifier made of `groupId` and `id`. In such a case, the endpoints for this entity will need to have both path variables, e.g.:  `@RequestMapping("/users/\{groupId}/\{id}")`.

=== Generated identifier

ifdef::todo[TODO: https://github.com/lightbend/kalix-runtime/issues/2724]

Finally, you can ask Akka to generate a unique identifier, this is typically useful when creating an Entity, and the id is a surrogate id. To indicate to Akka that an Entity id should be generated rather than extracted from the path, be sure to annotate the corresponding command method with `@GenerateId`. Typically, an Entity has only one method annotated with `@GenerateId`. The one that creates the Entity. All other methods will have `@Id` annotation in order to extract the surrogate id from the endpoint path.

It will often be necessary to access the generated entity id from inside the entities code. This can be done using the link:{attachmentsdir}/api/akka/javasdk/EntityContext.html#entityId()[`EntityContext.entityId`{tab-icon},window="new"] method.

NOTE: Kalix generates a UUID version 4 (random) keys. Only version 4 UUIDs are currently supported for generated Entity identifiers.
