= Welcome to Akka

Akka is a platform as a service (PaaS) to build and run distributed applications that are guaranteed to remain responsive to change. It abstracts the complexities of building distributed systems by providing an event-driven, stateful service model, allowing developers to focus on business logic rather than managing infrastructure and scalability.

[cols="1a,1a",frame="none",grid="none"]
|===

|
== Get Started

_Start here as an Akka developer:_

. Register for an https://console.akka.io/register[Akka account].
. Follow a guide to xref:java:getting-started.adoc[create your first service].
. Learn key patterns and abstractions by xref:samples:index.adoc[exploring the samples].

|
== How-To Guides

_Practical guides for:_

* xref:java:index.adoc[Developing Services]
* xref:operations:index.adoc[Operating Services]

|
== xref:concepts:index.adoc[Concepts]

_Essential principles, components and best practices for building with Akka._

|
== xref:reference:index.adoc[Reference]

_Technical reference for product updates, migration guides, and https://doc.akka.io/docs[Akka Libraries]._

|===
