= Using AWS MSK as Kafka service
include::ROOT:partial$include.adoc[]

Akka connects to https://aws.amazon.com/msk/[Amazon MSK, window="new"] clusters via TLS, authenticating using SASL (Simple Authentication and Security Layer) SCRAM.

Prerequisites not covered in detail by this guide:

. The MSK instance must be provisioned, serverless MSK does not support SASL.

. The MSK cluster must be set up with https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html[TLS for client broker connections and SASL/SCRAM for authentication, window="new"]
with a user and password to use for authenticating your Akka service

.. The user and password is stored in a secret

.. The secret must be encrypted with a specific key, MSK cannot use the default MKS encryption key

. The provisioned cluster must be set up for https://docs.aws.amazon.com/msk/latest/developerguide/public-access.html[public access, window="new"]

.. Creating relevant ACLs for the user to access the topics in your MSK cluster
.. Disabling `allow.everyone.if.no.acl.found` in the MSK cluster config

. Creating topics used by your Akka service

== Steps to connect to an AWS Kafka broker

Take the following steps to configure access to your AWS Kafka broker for your Akka project.

. Ensure you are on the correct Akka project
+
[source, command window]
----
akka config get-project
----

. Store the password for your user in an Akka secret:
+
[source, command window]
----
akka secret create generic aws-msk-secret --literal pwd=<sasl user password>
----

. Get the bootstrap brokers for your cluster, they can be found by selecting the cluster and clicking "View client information."
There is a copy button at the top of "Public endpoint" that will copy a correctly formatted string with the bootstrap brokers. https://docs.aws.amazon.com/msk/latest/developerguide/msk-get-bootstrap-brokers.html[See AWS docs for other ways to inspect the bootstrap brokers, window="new"].

. Use `akka projects config` to set the broker details. Set the MSK SASL username you have prepared and the bootstrap servers.
+
[source, command window]
----
akka projects config set broker  \
  --broker-service kafka \
  --broker-auth scram-sha-512 \
  --broker-user <sasl username> \
  --broker-password-secret aws-msk-secret/pwd \
  --broker-bootstrap-servers <bootstrap brokers> \
----

The `broker-password-secret` refer to the name of the Akka secret created earlier rather than the actual password string.

An optional description can be added with the parameter `--description` to provide additional notes about the broker.



The broker config can be inspected using:
[source, command window]
----
akka projects config get broker
----

=== Custom key pair

If you are using a custom key pair for TLS connections to your MSK cluster, instead of the default AWS provided key pair, you will need to define a secret with the CA certificate:

[source, command window]
----
akka secret create tls-ca kafka-ca-cert --cert ./ca.pem
----

And then pass the name of that secret for `--broker-ca-cert-secret` when setting the broker up:

[source, command window]
----
akka projects config set broker  \
  --broker-service kafka \
  --broker-auth scram-sha-512 \
  --broker-user <sasl username> \
  --broker-password-secret aws-msk-secret/pwd \
  --broker-ca-cert-secret kafka-ca-cert
  --broker-bootstrap-servers <bootstrap brokers> \
----


include::partial$broker-kafka-setup-common.adoc[]

== See also

- xref:reference:cli/akka-cli/akka_projects_config.adoc#_see_also[`akka projects config` commands]
