= Configure a container registry
:page-aliases: projects:projects/container-registries.adoc[]

include::ROOT:partial$include.adoc[]

Akka deploys services as container images. Your Akka services, and any dependencies they need, are sent to Akka as container images which can be produced using Maven (i.e. `mvn install`). Before deploying, the container must be made available for Akka in a container registry.

Akka provides a built-in _Akka Container Registry_ which is readily set up for your use. Alternatively, even xref:operations:projects/external-container-registries.adoc[external container registries] are supported with Akka.

== Akka Container Registry

The _Akka Container Registry_ (ACR) can be used by all Akka users to deploy services and is available in all Akka regions.

Using the ACR for deploying your Akka services is easy as authentication is built-in. Another benefit is that deployments, restarts and scaling does not depend on any connectivity to external registries.

== Prerequisites

Before continuing, the following prerequisites have to be checked.

- The current user must be logged in to Akka.
- You must have Docker installed and accessible to the current user.

Execute the `akka auth current-login` to verify that you are logged into Akka. (Use `akka auth login`, if not.)

[source,command line]
----
> akka auth current-login
ba6f49b0-c4e1-cccc-ffff-30053f652c42   user test@akka.io   true       CLI login from the machine.localdomain(127.0.0.1)   3d21h
----

Check that you have the Docker client installed.

[source,command line]
----
> docker --version
Docker version 27.3.1, build ce1223035a
----

== Configuring ACR authentication

The _Akka Container Registry_ uses an access token generated by Akka to authorize the user and determine if they can push images to the registry.

An intermediate credential helper generates the access token using the Akka CLI whenever a `docker push` command is issued. Use the Akka CLI to configure the Docker credentials helper:

[source,command line]
----
> akka auth container-registry configure
This operation will update your '.docker/config.json' file. Do you want to continue?
Use the arrow keys to navigate: ↓ ↑ → ←
? >:
  ▸ No
    Yes
----

Select "Yes" to continue.

When the command completes successfully, it lists the hostname of ACR for all available regions.

[source]
----
Docker configuration file successfully updated.
Available Akka Container Registry hosts per region:
REGION         ORGANIZATION   ORGANIZATION_ID                        AKKA CONTAINER REGISTRY
gcp-us-east1   PUBLIC         NONE                                   acr.us-east-1.akka.io
gcp-us-east1   acme           cde1044c-b973-4220-8f65-0f7d317bb458   acr.us-east-1.akka.io
----

The Akka Container Registry is now configured.

== Pushing an image to ACR

Pushing images to ACR works the same as pushing to any other Docker registry: using the Docker client, you tag an image and push it.

The fully qualified domain name of ACR for the current Akka region can be obtained using the CLI.

[source,command line]
----
> akka container-registry print
REGION         ORGANIZATION   ORGANIZATION_ID                        AKKA CONTAINER REGISTRY
gcp-us-east1   PUBLIC         NONE                                   acr.us-east-1.akka.io
gcp-us-east1   acme           cde1044c-b973-4220-8f65-0f7d317bb458   acr.us-east-1.akka.io
----

An image can be made available to a specific project or all projects within an organization. The image URL path selects the organization and project and the domain name selects the ACR region.

=== Image paths

The following paths are supported by ACR:

- Available to a **single project** `my-project` within an organization `acme`:
+
`acr.us-east-1.akka.io/acme/my-project/my-image:tag`

- Available to **all projects** with within the `acme` organization:
+
`acr.us-east-1.akka.io/acme/my-image:tag`

As you can see, the directory structure in ACR has the same structure as Akka in general, an organization has one or more projects that can host images.

Organizations can store images in the organizational root to enable deployment of the image in any project within the organization.

**For example:**

If we first push an image to the Acme organization.

[source,command line]
----
docker push acr.us-east-1.akka.io/acme/shopping-cart:latest
----

This image is now available to both the `stage` and `prod` projects in the `acme` organization.

== Configuring build tools for ACR

Your build tool can push the image for you instead. To do that, make sure to configure the image path on your project for the respective tool, as shown below.

[.tabset]
Maven::
Update your `pom.xml` with the ACR domain name and your Akka organization name
+
[source,xml]
.pom.xml
----
  <properties>
    ....
    <akkaContainerRegistry>acr.us-east-1.akka.io</akkaContainerRegistry>
    <akkaOrganization>acme</akkaOrganization>
    <dockerImage>${akkaContainerRegistry}/${akkaOrganization}/${project.artifactId}</dockerImage>
  </properties>
----
and run
+
[source,command line]
----
mvn deploy
----

== Deploying a service using an image from ACR

When deploying a Akka service specify the same image URL as above with the `akka service deploy` command:

Deploying a service as a member of the Acme organization.

[source,command line]
----
akka service deploy \
  shopping-cart-service \
  acr.us-east-1.akka.io/acme/shopping-cart:latest
----

Deploying a service as a member of the Acme organization, with an image in the project `my-trial-project`.

[source,command line]
----
akka service deploy \
  my-service \
  acr.us-east-1.akka.io/acme/my-trial-project/test-service:latest
----

== See also

- xref:reference:akka-cli/akka_container-registry.adoc#_see_also[`akka container-registry` commands]
