= Configure message brokers
include::ROOT:partial$include.adoc[]

Akka eventing integrates with https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub, window="new"] and managed Kafka services such as https://www.confluent.io/confluent-cloud[Confluent Cloud, window="new"] and https://aiven.io/kafka[Aiven for Apache Kafka, window="new"] to enable asynchronous messaging.

Message brokers are configured on Akka Project level. A project can have one broker configuration, Akka eventing is independent of the broker technology.

== Broker services

- xref:operations:projects/broker-aiven.adoc[Aiven for Apache Kafka]
- xref:operations:projects/broker-aws-msk.adoc[AWS MSK Kafka]
- xref:operations:projects/broker-confluent.adoc[Confluent Cloud]
- xref:operations:projects/broker-google-pubsub.adoc[Google Pub/Sub]

[#_testing]
== Testing Akka eventing

The Java SDK testkit has built-in support to simulate message brokers. See xref:java:consuming-producing.adoc#testing[Testing the Integration].

For running locally with a broker, see xref:java:running-locally.adoc#_local_broker_support[running a service with broker support].

[#_see_also]



== See also

- xref:reference:akka-cli/akka_projects_config.adoc#_see_also[`akka projects config` commands]
