= CLI
:page-aliases: cli:index.adoc[]

include::ROOT:partial$include.adoc[]

Using the Akka CLI, you control all aspects of your Akka account from your command line. With it, you create and deploy new services, stream logs, and invite new developers to join your projects.

== Installation

The Akka CLI, `akka` enables you to interact with Akka projects. To install it, follow these steps:
xref:operations:cli/installation.adoc[]

== Using the CLI

The Akka command-line interface (CLI) complements the browser-based https://console.akka.io[Akka Console, window="new"] user interface (UI), allowing you to perform deployment and configuration operations directly from the command line.
This page provides an overview of common commands: xref:operations:cli/using-cli.adoc[]

== Command Completion

Completion allows you to hit [TAB] on a partially entered `akka` command and have the shell complete the command, subcommand or flag for you.
To enable it, follow these steps: xref:operations:cli/command-completion.adoc[]
