= Process overview
include::ROOT:partial$include.adoc[]

The main steps in developing a service include:

. <<_specify_service_interface_and_domain_model>>
. <<_effects_api>>
. <<_implement_components>>
. <<_create_unit_tests>>
. <<_package_service>>
. <<_run_locally>>
. <<_deploy_to_kalix>>


[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

The main components of an Akka service are:

* Stateful https://docs.kalix.io/reference/glossary.html#entity[Entities]
* Stateless https://docs.kalix.io/reference/glossary.html#action[Actions]
* https://docs.kalix.io/reference/glossary.html#view[Views], which return the state of multiple instances of a stateful entity.

We recommend that you separate the service API and Entity domain data model in individual `.proto` files, as https://grpc.io[gRPC] descriptors. Separating the service interface and data model in different files allows you to evolve them independently.

The gRPC definitions in `.proto` files describe the external interface, messages, and events. From the `.proto` files, the gRPC CLI (`protoc`), generates the code framework for remote procedure calls, data access, and serialization.

TIP: Kickstart a project using the xref:java:getting-started.adoc[project template].

include::java:partial$effects-api.adoc[]

[#_implement_components]
== Implement components

Stateful services can implement https://docs.kalix.io/reference/glossary.html#value_entity[Key Value Entity] or https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entity] and https://docs.kalix.io/reference/glossary.html#view[View] components. Stateless services implement https://docs.kalix.io/reference/glossary.html#action[Actions]. Typically, a stateful service should only have one Entity type, but can also include Actions and Views.


=== Endpoints

ifdef::todo[TODO: describe endpoints]

=== Entities
Stateful services encapsulate business logic in Key Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.


TIP: To learn more about Akka entities see xref:java:value-entity.adoc[Implementing Key Value Entities] and xref:java:event-sourced-entities.adoc[Implementing Event Sourced Entities].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

=== Endpoints

ifdef::todo[TODO: describe workflows]

=== Consumers

ifdef::todo[TODO: describe consumers]

=== Views

A View provides a way to retrieve state from multiple Entities based on a query. You can create views from Key Value Entity state, Event Sourced Entity events, and by subscribing to topics. For more information about writing views see xref:java:views.adoc[Implementing Views].

=== Timed actions

ifdef::todo[TODO: describe timed actions]

For more details and examples take a look at the following topics:

* xref:java:endpoints.adoc[Endpoints]
* xref:java:value-entity.adoc[Key Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:workflows.adoc[Workflows]
* xref:java:consuming-producing.adoc[Consumers]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed actions]

[#_create_unit_tests]
== Create unit tests

It is good practice to write unit tests as you implement your services. The kickstart codegen project includes hooks for JUnit testing. For implementation details see the xref:java:getting-started.adoc[Project template].

[#_package_service]
== Package service

Use Docker to package your service and any of its dependencies.
See https://docs.kalix.io/projects/container-registries.html[Configuring registries] for more information.


[#_run_locally]
== Run locally

You can test and debug your services by xref:java:running-locally.adoc[running them locally] before deploying to Akka.

[#_deploy_to_kalix]
== Deploy to Akka

After testing locally, deploy your service to Akka using the CLI or the Console. The following pages provide information about deployment:

* https://docs.kalix.io/projects/index.html[Working with Akka projects]
* https://docs.kalix.io/services/deploy-service.html#_deploy[Deploying a packaged service]
