= Managing organization users
include::ROOT:partial$include.adoc[]
:page-supergroup-console-cli: Interface

Access to an organization is controlled by assigning roles to users. The available roles are: *superuser*, *project-admin*, *billing-admin*, and *member*.

[cols="1,1,1,1,1"]
|===
|Permission                           |superuser |project-admin |billing-admin| member

|View organization users              |✅         |✅            |✅    |✅    
|Manage organization users            |✅         |❌            |❌    |❌   
|Create projects                      |✅         |✅            |❌    |❌
|View projects                        |✅         |❌            |❌    |❌
|Manage project users                 |✅         |❌            |❌    |❌
|Delete projects                      |✅         |❌            |❌    |❌
|All other project/service operations |❌         |❌            |❌    |❌
|View organization billing data       |❌         |❌            |✅    |❌ 
|===

NOTE: Project-level operations are accessed via project-specific roles. A superuser has a subset of project permissions, including the ability to assign roles (including to themselves). When a user creates a project, they are automatically granted admin access to it. (see xref:operations:projects/manage-project-access.adoc[granting project roles])

The *member* role allows project admins to add users to their projects without needing to invite them to the organization.

== Listing role bindings
[[managing-organization-users-list-role-bindings]]

You can list role bindings within an organization using the following command:

[source,command window]
----
akka organization users list-bindings --organization <organization name>
----

Example output:
[source]
----
ROLE BINDING ID                        ROLE        USERNAME       EMAIL                      NAME
fd21044c-b973-4220-8f65-0f7d317bb23b   superuser   jane.citizen   jane.citizen@example.com   Jane Citizen
120b75b6-6b53-4ebb-b23b-2272be974966   member      john.smith     john.smith@example.com     John Smith
----

== Granting a role

You can grant a role to a user in two ways:

==== 1. Invite a User by Email
Send an email invitation with the following command:

[source,command window]
----
akka organizations invitations create --organization <organization name> \
  --email <email address> --role <role>
----

The user will receive an email to join the organization. Once accepted, the role binding will be created.


==== 2. Add a Role Directly

If the user is already a member, you can assign roles directly:

* By e-mail:
[source,command window]
----
akka organization users add-binding --organization <organization name> \
  --email <email address> --role <role>
----

* By username:
[source,command window]
----
akka organizations users add-binding --organization <organization name> \
  --username <username> --role <role>
----

== Deleting a role binding

To delete a role binding, first list the users to get the role binding ID. Then, use the following command:

[source,command window]
----
akka organizations users delete-binding --organization <organization name> \
  --id <role binding id>
----

== Managing invitations

View outstanding invitations:


[source,command window]
----
akka organizations invitations list --organization <organization name>
----

Example output:
[source]
----
EMAIL                      ROLE
jane.citizen@example.com   member
----

Invitations expire after 7 days, but you can cancel them manually:

[source,command window]
----
akka organizations invitations cancel --organization <organization name> \
  --email <email address>
----

To resend an invitation, cancel the previous one and reissue the invite.

== See also

- xref:projects/manage-project-access.adoc[]
- xref:reference:cli/akka-cli/akka_organizations_users.adoc#_see_also[`akka organizations users` commands]
- xref:reference:cli/akka-cli/akka_organizations_invitations.adoc#_see_also[`akka organizations invitations` commands]
