= Securing

include::ROOT:partial$include.adoc[]

Akka offers multiple levels of authentication and authorization that can be used to secure services, projects and organizations. Which levels are right for you will depend greatly on your use case. These levels of security are complementary. In some cases, it may make sense to utilize multiple levels of Akka security features.

== Service level

The features for securing services that Akka supports are:

* xref:security:acls.adoc[Access Control Lists (ACLs)]
* xref:security:tls-certificates.adoc[Client certificates]
* xref:security:jwts.adoc[JSON Web Tokens (JWTs)]

== Project level

Access to projects is managed by granting users roles. Different roles enable different capabilities when interacting with a project. To understand which roles exist and how to assign them, refer to the section xref:operations:projects/manage-project-access.adoc[]. Project membership is managed via the `akka roles` commands.

To allow for scripted access to projects, Akka supports authentication tokens. For details see xref:operations:integrating-cicd/index.adoc[].

Akka also provides secret management for each project, typically used for passwords, login credentials, keys, etc. You can provide secrets to your services through environment variables. For details see xref:operations:projects/secrets.adoc[] section.


== Organization level

Similarly to projects, access to organizations is managed by granting users roles that provide different capabilities. To understand which roles exist and how to assign them, consult the section xref:operations:organizations/manage-users.adoc[]. Organization membership is managed via the `akka organization invitations` and `akka organization users` commands.

=== Single Sign-On

Akka supports Single Sign-On (SSO) integration via *OpenID Connect* with third party providers such as https://auth0.com[Auth0], https://www.okta.com/products/single-sign-on-customer-identity/[Okta], and others. The Akka CLI supports configuring the desired OpenID Connect integration. Please enquire our xref::support:email.adoc[Support via the contact form] for details.

=== Multifactor authentication (MFA)

Users accounts in Akka may be protected with _multifactor authentication_ (MFA) for increased security. Organizations in Akka can require their members to set up MFA before joining the organization. Please enquire our xref::support:email.adoc[Support via the contact form] for details.

=== Audit logging for operating Akka services

Akka records all executed commands when operating services for audit logging purposes. Please enquire our xref::support:email.adoc[Support via the contact form] for details.
