= Release Notes
:page-aliases: release-notes:index.adoc

include::ROOT:partial$include.adoc[]

== Aug 2024
image:Feature.svg[width=100] kalix CLI 2.0.49: Organizations get command for organization details. More detailed region information is now displayed.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.5.2[Kalix JVM SDKs 1.5.2, window=_blank] Automatically passing metadata traceparent in Actions, adding missing tracing MDC for views, and other various improvements.

== July 2024

image:Fixed.svg[width=100] kalix CLI 2.0.48: Bug fix where principals were not being printed to the console whilst listing bindings

image:Feature.svg[width=100] kalix CLI 2.0.47: Select a default Organization for subsequent commands

image:Fixed.svg[width=100] kalix CLI 2.0.47: Bug fix for output formats

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.5.1[Kalix JVM SDK 1.5.1, window=_blank] Logging now supports https://docs.kalix.io/operations/view-logs.html#_correlating_logs[correlation with trace IDs].

== May 2024

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.5.0[Kalix JVM SDK 1.5.0, window=_blank] release we change our license to https://github.com/lightbend/kalix-jvm-sdk/blob/main/LICENSE[Business Source License (BSL), window=_blank]. This change allows the Kalix SDK to make use of the latest enhancements in Akka 2.9 and other Akka libraries. Furthermore, with this even the Kalix SDK is covered by Lightbend's SOC2 compliance. Please refer to the https://www.lightbend.com/legal/terms[Lightbend Legal terms, window=_blank] page for details.

image:Feature.svg[width=100] New features include support for Scala 3 in the Scala Protobuf SDK and component to component tracing now available even for the Java SDK.

image:Changed.svg[width=100] A minor build migration is needed when updating to Kalix JVM SDK 1.5.0. See the migration guide xref:migration-guide.adoc[here].

image:Deprecated.svg[width=100] Some deprecated APIs have been removed in Kalix JVM SDKs 1.5.0. Please refer to the migration guide xref:migration-guide.adoc[here] for more details.

image:Changed.svg[width=100] The license for Kalix JavaScript SDK has also been changed to https://github.com/lightbend/kalix-javascript-sdk/blob/main/LICENSE[Business Source License (BSL), window=_blank]. This change is to align with the licensing of our other SDKs. Please refer to the https://www.lightbend.com/legal/terms[Lightbend Legal terms, window=_blank] page for details.

image:Feature.svg[width=100] Additional features in the https://docs.kalix.io/reference/kalix/index.html[Kalix CLI], including support for developing locally with https://docs.kalix.io/reference/kalix/kalix_local_run.html[`kalix local run`].
The new https://docs.kalix.io/reference/kalix/kalix_services_views_describe.html[`kalix services views describe`] command shows detailed information about a Kalix View.


== March 2024

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.4.1[Kalix JVM SDKs 1.4.1, window=_blank] Support for tracing component and external calls and other various improvements.


== February 2024

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.4.0[Kalix JVM SDKs 1.4.0, window=_blank] Adds support for workflows in Java and Scala Protobuf SDKs, see xref:java-protobuf:workflows.adoc[here]. Additionally, this version extends View component to support multiple queries to the same table.

image:Deprecated.svg[width=100] Deprecations introduced in https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.4.0[Kalix JVM SDKs 1.4.0, window=_blank]

Java and Scala Protobuf SDKs:

* `(kalix.field).entity_key` is replaced with `(kalix.field).id`
* `(kalix.method).entity.key_generator` is replaced with `(kalix.method).id_generator.algorithm`
* `(kalix.codegen).entity_type` is replaced with `(kalix.codegen).type_id`

Old annotations are deprecated and will be removed in the next major release.

Java SDK:

* class `kalix.javasdk.workflow.Workflow.RecoverStrategy` was moved to `kalix.javasdk.workflow.AbstractWorkflow.RecoverStrategy`, please update your code accordingly.

== January 2024

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.8[Kalix JVM SDKs 1.3.8, window=_blank] Adds support for on-startup hook in Java SDK, see xref:java:actions.adoc#_actions_as_life_cycle_hooks[here]. Introduces ability to require multiple values for a JWT static claim and defining it with a regex pattern, see xref:java:using-jwts.adoc#_using_static_claims[here]. General fixes and improvements.

== December 2023

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.7[Kalix JVM SDKs 1.3.7, window=_blank] Fixes and improves the broken Maven Archetypes.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.6[Kalix JVM SDKs 1.3.6, window=_blank] Views' enhancements for when doing aggregations. Ability to declare an on-startup hook which will be triggered automatically on instance startup (currently available for Java/Scala Protobuf SDKs, see xref:java-protobuf:actions.adoc#_actions_as_life_cycle_hooks[here]). Support for JWT static claims (see xref:java-protobuf:using-jwts.adoc#_using_static_claims[docs]).

image:Feature.svg[width=100] The xref:reference:kalix/kalix_container-registry.adoc[`kalix container-registry`] commands have been added to assist in managing your assets in the Kalix Container Registry.

image:Feature.svg[width=100] HTTP/1.1 support for `kalix` commands. The `kalix` CLI uses gRPC to communicate with many backend Kalix services, which requires HTTP/2. In some corporate environments, decrypting transparent proxies are used which don't support HTTP/2, preventing the `kalix` CLI from working. This adds a new option to tell `kalix` to use grpc-web when communicating with backend services, which works over HTTP/1.1.

== November 2023

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.5[Kalix JVM SDKs 1.3.5, window=_blank] Support for JUnit 5. Fix regression introduced in v1.3.4 affecting the use of `KalixClient` and `ComponentClient`. General documentation improvements.

image:Feature.svg[width=100] xref:reference:kalix/kalix_local.adoc[`kalix local`] command has been added to assist in running and managing Kalix services locally.

image:Feature.svg[width=100] Route validations can now be configured. Routes can be protected by xref:operations:invoke-service.adoc#_http_basic_authentication[HTTP Basic authentication], and, when using client certificates, xref:security:tls-certificates.adoc#_client_certificate_validation[client certificate subjects] can be validated.

image:Feature.svg[width=100] Google Cloud logs and metrics exporters can now xref:operations:observability-exports.adoc#_google_cloud[be configured]. This replaces the old Stackdriver log aggregator support.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.4[Kalix JVM SDKs 1.3.4, window=_blank] Support for mocked Service-to-Service and View subscriptions in Integrations tests (make sure to update your current test kit xref:java:actions-publishing-subscribing.adoc#_configuration[configuration]). New service-level JWT configuration that reduces boilerplate and allows for a deny-by-default policy.

== September 2023

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.3[Kalix JVM SDKs 1.3.3, window=_blank] Support for JSON Schema Evolution in Java SDK. Improvements in Workflows and TestKit Mocked Topic.

== August 2023

image:Feature.svg[width=100] Splunk HEC CLI configuration support

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.1.0[Kalix JavaScript/TypeScript SDK 1.1.0, window=_blank] Updated to Node 18 (Active LTS).

image:Feature.svg[width=100] Adds the ability to configure observability for a Kalix project via `projects observability` in the Kalix CLI.

== July 2023

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.2[Kalix JVM SDKs 1.3.2, window=_blank] Support ComponentClient in integration tests and some bug fixes.

image:Feature.svg[width=100] Allow users to set their own Kafka message broker with SASL authentication by using xref:reference:kalix/kalix_projects_config_set_broker.adoc[kalix project config set broker] with arguments `--broker-auth`, `--broker-bootstrap-servers`, `--broker-user`, `--broker-password-secret` and `--broker-password-secret`. Deprecated the argument `--broker-config-file`.

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.1[Kalix JVM SDKs 1.3.1, window=_blank] Kalix TestKit `EventingSupport` enum for PubSub renamed from `EventingSupport.GOOGLE_PUBSUB_EMULATOR` to `EventingSupport.GOOGLE_PUBSUB`.

== June 2023

image:Feature.svg[width=100] Introduced the `secrets create tls` command in the Kalix CLI. Support to show exceptions in Kalix logs.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.0[Kalix JVM SDKs 1.3.0, window=_blank] xref:java:workflows.adoc[Kalix Workflow] GA release.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.0[Kalix JVM SDKs 1.3.0, window=_blank] ComponentClient for type-safe deferred calls creation. Also, deprecating existing KalixClient. 

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.0[Kalix JVM SDKs 1.3.0, window=_blank] TestKit Mocked Topics for easier integration tests with brokers (for Java SDK, see https://docs.kalix.io/java/actions-publishing-subscribing.html#_testkit_mocked_topic[here, window=_blank]).

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.0[Kalix JVM SDKs 1.3.0, window=_blank] Default broker used in Integration Tests is no longer Google PubSub but can still be enabled via settings for each test.

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.3.0[Kalix JVM SDKs 1.3.0, window=_blank] New annotations `@Id`, `@TypeId` and `@GenerateId` to replace `@EntityKey`, `@EntityType` and `@GenerateEntityKey` respectively. `@EntityKey`, `@EntityType` and `@GenerateEntityKey` are deprecated as of release Kalix Java SDK 1.3.0.

image:Feature.svg[width=100] Java and Java/Protobuf SDK new plugin goal (`mvn kalix:runAll`) allows the start of Kalix Proxy from within the Maven plugin.

image:Feature.svg[width=100] Scala/Protobuf SDK new plugin goal (`sbt runAll`) allows the start of Kalix Proxy from within the sbt plugin.

image:Feature.svg[width=100] Multi-service testing for xref:java:running-locally.adoc#_running_multiple_services_locally[Java], xref:java-protobuf:running-locally.adoc#_running_multiple_services_locally[Java/Protobuf and Scala/Protobuf SDKs].

== May 2023
image:Feature.svg[width=100] Allow users to set/update their own TLS certificate for the Ingress by using xref:reference:kalix/kalix_routes_create.adoc[kalix routes create] and xref:reference:kalix/kalix_routes_update.adoc[kalix routes update] with argument `--server-certificate-secret` (and `--remove-server-certificate-secret` for the update command).

image:Feature.svg[width=100] Show expired trial projects in CLI and Web UI.

== April 2023
image:Feature.svg[width=100] Enable multi-platform proxy docker image build to improve developer experience for Mac users with Apple silicon processors.

image:Feature.svg[width=100] Allow users to set the description of a broker configuration by using xref:reference:kalix/kalix_projects_config_set_broker.adoc[kalix project config set broker] with argument `--description`.

image:Feature.svg[width=100] Display the project's region when using xref:reference:kalix/kalix_projects_list.adoc[kalix projects list] and xref:reference:kalix/kalix_projects_get.adoc[kalix project get].

== March 2023
image:Feature.svg[width=100] Allow users to configure autoscaling of a service using xref:reference:kalix/kalix_services_deploy.adoc[kalix service deploy] with arguments `--max-instances` and `--min-instances`.

image:Feature.svg[width=100] New service commands xref:reference:kalix/kalix_services_apply.adoc[kalix service apply] and xref:reference:kalix/kalix_services_export.adoc[kalix service export] to apply and export YAML descriptors for services.

image:Feature.svg[width=100] Second preview of Kalix Workflows.

image:Changed.svg[width=100] Improve CLI help for xref:reference:kalix/kalix_routes_create.adoc[kalix routes create] and xref:reference:kalix/kalix_routes_update.adoc[kalix routes update]

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.2.0[Kalix JVM SDKs 1.2.0, window=_blank] Protocol-first Java/Scala SDKs are renamed to Java/Scala **Protobuf** SDKs and code-first Spring SDK is renamed to Java SDK. Users of Java/Protobuf SDK need to update the artifact name. See https://github.com/lightbend/kalix-jvm-sdk/blob/main/docs/migration-guides.md[migration guide, window=_blank].

== February 2023

image:Feature.svg[width=100] New xref:operations:billing.adoc[Billing UI] for Organizations

image:Feature.svg[width=100] First preview of Kalix Workflows.

image:Feature.svg[width=100] Improved auto restarting in dev mode.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.7[Kalix Java SDK 1.1.7, window=_blank] Fix allowing the use of `Instant` in Spring SDK views.

== January 2023

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.5[Kalix Java SDK 1.1.5, window=_blank] Several developer experience improvements.

== December 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.4[Kalix Java SDK 1.1.4, window=_blank] Fix for Replicated Entities in the Scala SDK. Support xref:java:views.adoc#_advanced_view_queries[advanced views] in the Spring SDK.

image:Changed.svg[width=100] Performance improvements of View updates. Views can keep up with a higher event throughput.

image:Changed.svg[width=100] Performance improvements of timers. Can handle more short lived and more active timers. Also limits timer payload size and total number of accepted timers.

image:Changed.svg[width=100] Lower latency for `eventing.in` from Event Sourced Entity, including Service to Service eventing.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.3[Kalix Java SDK 1.1.3, window=_blank] Support xref:java-protobuf:views.adoc#_advanced_view_queries[advanced views] with join queries. Allow `ignore` as an async effect in Actions.

== November 2022

image:Feature.svg[width=100] Delete handlers for Views and Actions.

image:Feature.svg[width=100] The Kalix Console now shows service statuses (such as "Paused").

image:Feature.svg[width=100] CLI command xref:reference:kalix/kalix_projects_rename.adoc[kalix projects rename] to rename an existing Kalix project.

image:Feature.svg[width=100] The CLI command xref:reference:kalix/kalix_services_get.adoc[kalix services get] now includes the status of the service.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.2[Kalix Java SDK 1.1.2, window=_blank] Fixes and improvements on the Kalix Spring SDK.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.1[Kalix Java SDK 1.1.1, window=_blank] Fixes and improvements. TestKit updated to proxy 1.0.28.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.0[Kalix Java SDK 1.1.0, window=_blank] First release that officially includes the new Spring SDK (beta) - find the documentation https://docs.kalix.io/spring/index.html[here].

image:Changed.svg[width=100] ACLs are now by default disabled for local development starting from Java/Scala SDK version 1.0.11 and JavaScript SDK version 1.0.5. Consult Local development with ACLs section as well the specific SDK pages for details on how to enable it for tests (https://docs.kalix.io/java/access-control.html#_acls_when_running_integration_tests[Java/Scala] or https://docs.kalix.io/javascript/access-control.html#_acls_when_running_integration_tests[JavaScript])

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.5[Kalix JavaScript SDK 1.0.5, window=_blank]

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.11[Kalix Java SDK 1.0.11, window=_blank]

image:Feature.svg[width=100] Support Kalix Console login with MFA (Multi-factor Authentication) https://console.kalix.io/settings[settings].

image:Feature.svg[width=100] Support service soft delete with the commands xref:reference:kalix/kalix_services_delete.adoc[kalix services delete] and xref:reference:kalix/kalix_services_restore.adoc[kalix services restore].

image:Feature.svg[width=100] New service commands for pausing and resuming a service - xref:reference:kalix/kalix_services_pause.adoc[kalix services pause] and xref:reference:kalix/kalix_services_resume.adoc[kalix services resume].

image:Feature.svg[width=100] CLI command xref:reference:kalix/kalix_docs.adoc[kalix docs] to open online documentation.

image:Feature.svg[width=100] Display organization contract number in xref:reference:kalix/kalix_organizations_list.adoc[kalix organization list].

== October 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.10[Kalix Java SDK 1.0.10, window=_blank]

image:Changed.svg[width=100] Deprecation of the `--shell` flag for the `kalix completion` command.

image:Feature.svg[width=100] xref:reference:kalix/kalix_services_views.adoc[CLI view commands for managing views added]

image:Feature.svg[width=100] Service to Service eventing - brokerless at-least-once eventing between Kalix services.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.9[Kalix Java SDK 1.0.9, window=_blank] Support and docs for Service to Service eventing.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.4[Kalix Javascript/Typescript SDK 1.0.4, window=_blank] Support for Service to Service eventing.

== September 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.8[Kalix Java SDK 1.0.8, window=_blank] New Spring SDK preview available.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.7[Kalix Java SDK 1.0.7, window=_blank] 

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.6[Kalix Java SDK 1.0.6, window=_blank] Parallel request handling bug fix


== August 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.3[Kalix JavaScript SDK 1.0.3, window=_blank] Fix for codegen binary on Windows.

image:Feature.svg[width=100] Service tokens - users can now create tokens for third party services, such as CI/CD, that are associated with a single project, rather than a logged in user, so that those tools can interact with projects having only the permissions they need. See xref:operations:integrate-cicd.adoc[Integrate with CI/CD tools] for more details.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.2[Kalix JavaScript SDK 1.0.2, window=_blank] Fix for codegen binary on Linux.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.1[Kalix JavaScript SDK 1.0.1, window=_blank] Fix for `protobufjs` transitive dependency and missing `pbjs` and `pbts` binaries.

image:Feature.svg[width=100] Users can now have different roles in their Organizations and Projects. See xref:operations:manage-users.adoc[Managing organization users] and xref:operations:manage-project-access.adoc[Managing project users] for more details.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.5[Kalix Java SDK 1.0.5, window=_blank] Internal networking improvements.

image:Feature.svg[width=100] Organization administrators can now manage user roles within their organization. See xref:reference:kalix/kalix_organizations_users_add-binding.adoc[Add a role binding] for more details.

== July 2022

image:Feature.svg[width=100] Invitations to organizations can now be cancelled via the Kalix CLI. See xref:operations:organizations.adoc[Organizations] for more details.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.0[Kalix JavaScript SDK 1.0.0, window=_blank] Full TypeScript support. New Quickstart documentation.

image:Feature.svg[width=100] More efficient way of ignoring events in Actions and Views, https://docs.kalix.io/java/actions-publishing-subscribing.html#_ignoring_events[see documentation].

== June 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v1.0.0-M10[Kalix JavaScript SDK 1.0.0-M10, window=_blank] TypeScript API and tooling improvements. ACL support added. Preliminary support for building projects on Apple M1.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.3[Kalix Java SDK 1.0.3, window=_blank] ACL support.

== May 2022

image:Feature.svg[width=100] Pass through JSON, text and bytes from HTTP endpoints

image:Feature.svg[width=100] ACL support: Access Control Lists for authorizing access to Kalix services

image:Feature.svg[width=100] Timers providing scheduled service calls

== April 2022

image:Feature.svg[width=100] Projects can now belong to an organization. Users can be invited to become part of an organization via the Kalix CLI. See xref:operations:organizations.adoc[Organizations] for more details.

image:Feature.svg[width=100] image:Changed.svg[width=100] The query language in Views has been extended significantly.

image:Feature.svg[width=100] The all new web interface has been launched at https://console.kalix.io[console.kalix.io, window=_blank].

== March 2022

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v0.33.5[Kalix JavaScript SDK 0.33.5, window=_blank] Fix proto to JS code generation.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v0.33.4[Kalix JavaScript SDK 0.33.4, window=_blank] Support emitting JSON to topics.

== January 2022

image:Feature.svg[width=100] image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.10.1[Kalix Java SDK 0.10.5, window=_blank] Support for paging in views.

image:Feature.svg[width=100] JWT support: validate messages against the JWT bearer token; specify multiple trusted issuers; allow local testing with JWT

image:Feature.svg[width=100] Entity keys can now be generated by Kalix actions.

== December 2021

image:Feature.svg[width=100] You can now secure your services with client certificates and/or JWTs. See xref:security:index.adoc[Securing services] for more details. You will need version 0.1.9 of the Kalix CLI to use this.

image:Feature.svg[width=100] You can now querying repeated nested message fields in views.

image:Feature.svg[width=100] You can now receive byte string and text messages from topics.

image:Feature.svg[width=100] The root package is now configurable, which is important when your `.proto` definitions don't share a common parent package when using the Java/Scala SDK.

image:Feature.svg[width=100] Component names can now be explicitly specified when using the Java/Scala SDK.

== November 2021

image:Changed.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.10.1[Kalix Java SDK 0.10.1, window=_blank] smaller fixes and improvements including a code generation solving Scala and Java quickstart sample issues.

image:Feature.svg[width=100] You can now use Kafka to connect your Kalix services together and to connect to external services as well.

image:Changed.svg[width=100] We've updated the messages that are logged in your projects so it is easier to see which messages you should act on and what they mean.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.10.0[Kalix Java SDK 0.10.0, window=_blank] is now available with a new type safe generated API for interaction between components in the same service.

image:Feature.svg[width=100] We've introduced our new secrets management API. To safely and securely store secrets you'll need version 0.1.6 of the Kalix CLI.

== October 2021

image:Changed.svg[width=100] We've implemented a new feature that automatically scales your service down to zero when it fails to start 3 times in a row. This helps preserve your trial credits.

image:Changed.svg[width=100] The minimum required Java version is now Java 11.

image:Feature.svg[width=100] A new version of the Kalix CLI (v 0.1.1) is now available! You'll need this latest version to make use of the new platform capabilities

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.9.0[Kalix Java/Scala SDK 0.9.0, window=_blank] is now available and contains all entity types!

image:Feature.svg[width=100] As a new state model, we've introduced our Replicated Entities. Replicated Entities distribute state using a conflict-free replicated data type (CRDT). Data is shared across multiple instances of a Replicated Entity and is eventually consistent to provide high availability with low latency.

image:Feature.svg[width=100] We've added a lot of new quickstarts to help you get started with Kalix even faster.

image:Feature.svg[width=100] We've added documentation on how you can call Kalix services from other Kalix services in your project.

== September 2021

image:Feature.svg[width=100] A new version of the Kalix CLI (v 0.0.39) is now available! We strongly recommend upgrading to the latest version to make use of the new `quickstarts` command.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.7.0[Kalix Java SDK 0.7.0, window=_blank] is now available! This is massive rewrite of the SDK to align our different APIs, remove reflection magic, have a better typed system, and introduce a new generated TestKit.

image:Deprecated.svg[width=100] We’ve deprecated the `entity generate` command in the Kalix CLI in favor of the new code generation capabilities of the SDKs.

image:Feature.svg[width=100] There is a new section in the documentation, Quickstarts, to help you get started with Kalix.

image:Feature.svg[width=100] We've introduced a new (and easy) way to give feedback on the documentation. Click on the little blue icon (with the thumbs) to give us feedback.

image:Changed.svg[width=100] The Kalix CLI will now periodically update the cached data.

== August 2021

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.7.0-beta.19[Kalix Java SDK 0.7.0-beta.19, window=_blank] is now available!

image:Changed.svg[width=100] We’ve added docs to show how to leverage GitHub Actions and CircleCI to deploy services to Kalix

image:Feature.svg[width=100] To make it easier to test your services, the Service Explorer now generate gRPCurl, cURL, and Fetch commands you can copy/paste

image:Feature.svg[width=100] To make it easier to get started you’re now guided through an onboarding wizard to create a project, download the CLI, and find the tutorials

image:Changed.svg[width=100] We’ve updated the SDK support page to make it easier to see which SDKs are in which tier

image:Feature.svg[width=100] The Kalix CLI now has a new required flag region when you create a new project using the CLI.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v0.33.0[Kalix JavaScript/Typescript SDK 0.33.0, window=_blank] is now available!

== July 2021

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.7.0-beta.18[Kalix Java SDK 0.7.0-beta.18, window=_blank] is now available!

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v0.32.0[Kalix JavaScript/Typescript SDK 0.32.0, window=_blank] is now available!

image:Feature.svg[width=100] You can now add container registry credentials from within the console, on the "Integrations" tab.

image:Changed.svg[width=100] We've made changes to the support form, so it'll be easier for us to help you troubleshoot an issue.

image:Changed.svg[width=100] When you're inviting a new user, we now also show the invite URL in the console so you can send the URL to the new project member.

image:Feature.svg[width=100] https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v0.7.0-beta.15[Kalix Java SDK 0.7.0-beta.15, window=_blank] is now available!

image:Feature.svg[width=100] https://github.com/lightbend/kalix-javascript-sdk/releases/tag/v0.31.0[Kalix JavaScript/Typescript SDK 0.31.0, window=_blank] is now available!

== June 2021

image:Feature.svg[width=100] If you don't like your project anymore, you can now delete it and start a brand new one.

image:Feature.svg[width=100] The `kalix` CLI now natively runs on Apple Silicon chips.

image:Feature.svg[width=100] The Kalix JavaScript SDK now ships TypeScript definitions to make development even easier.

image:Feature.svg[width=100] The Kalix JavaScript SDK now supports asynchronous user functions.

image:Feature.svg[width=100] Added new account menu to the header bar in the Kalix Console.

image:Changed.svg[width=100] The help menu items from the left navigation bar have move to a help menu in the header bar.

== May 2021

image:Changed.svg[width=100] Updated the user interface to be consistent across various screens.

image:Changed.svg[width=100] Updated log format for the CLI to match the Web UI.

image:Feature.svg[width=100] Added integration to Google Cloud Pub/Sub.

image:Feature.svg[width=100] With the ability to connect to Google Cloud Pub/Sub we've also added new samples for our Java and JavaScript SDKs.

== April 2021

image:Changed.svg[width=100] As we get ready for our open beta, you no longer need to get projects approved.

image:Changed.svg[width=100] To protect our users' applications and our platform, we've limited the ports that are open by default. If you need additional ports opened, send us a note.

== March 2021

image:Feature.svg[width=100] Added a new “integrations” section from where you can connect to Google Cloud’s operation suite (formerly Stackdriver).

image:Feature.svg[width=100] Created new versions of the code generation for Node.js and Java.

image:Changed.svg[width=100] There’s a new indicator that shows the Project ID field, which is useful when contacting the support team.

image:Changed.svg[width=100] Updated the log section to show more details, show an icon of the log level, and make filtering of the logs possible from the UI.

image:Feature.svg[width=100] With the introduction of Views, you can now query your entities using SQL.

image:Feature.svg[width=100] Adding a new State Model to the mix, you can now use Value Entities using the Java and JavaScript SDKs.
