= akka services components

Manage the components of a service.

== Options

----
  -h, --help   help for components
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running kalix commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable KALIX_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_services.html[akka services]	 - Manage and deploy services on Akka.
* link:akka_services_components_get-state.html[akka services components get-state]	 - List the state for the given service, stateful component name and ID
* link:akka_services_components_get-workflow.html[akka services components get-workflow]	 - Get workflow execution details for the specified service, workflow component name and id
* link:akka_services_components_list.html[akka services components list]	 - List the components served by this service.
* link:akka_services_components_list-events.html[akka services components list-events]	 - List events from the Event Sourced Entity for the given service, component and entity id
* link:akka_services_components_list-ids.html[akka services components list-ids]	 - List the IDs for the given named stateful component served by this service.
* link:akka_services_components_list-timers.html[akka services components list-timers]	 - List the timers registered in this service.

[discrete]

