= akka projects

Manage your Akka projects.

== Synopsis

The `akka projects` commands manipulate the projects in your Kalix account, where a project is a collection of services.

== Options

----
  -h, --help   help for projects
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running kalix commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable KALIX_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka.html[akka]	 - Akka control
* link:akka_projects_config.html[akka projects config]	 - Manage project configs.
* link:akka_projects_delete.html[akka projects delete]	 - Delete a project.
* link:akka_projects_get.html[akka projects get]	 - Get project information.
* link:akka_projects_hostnames.html[akka projects hostnames]	 - Manage hostnames for your Akka project.
* link:akka_projects_list.html[akka projects list]	 - List all projects.
* link:akka_projects_new.html[akka projects new]	 - Create a new Akka project.
* link:akka_projects_observability.html[akka projects observability]	 - Manage the observability settings for your Akka project
* link:akka_projects_open.html[akka projects open]	 - Opens the current project in the console.
* link:akka_projects_regions.html[akka projects regions]	 - Manage the regions for your Akka project
* link:akka_projects_tokens.html[akka projects tokens]	 - Manage your Akka project service tokens
* link:akka_projects_update.html[akka projects update]	 - Update project attributes such as name and description.

[discrete]

