= akka projects observability

Manage the observability settings for your Akka project

== Synopsis

The `akka project observability` command manages the observability settings for your Kalix project.

== Options

----
  -h, --help   help for observability
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running kalix commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable KALIX_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_projects.html[akka projects]	 - Manage your Akka projects.
* link:akka_projects_observability_apply.html[akka projects observability apply]	 - Applies an observability descriptor to the currently configured project.
* link:akka_projects_observability_config.html[akka projects observability config]	 - Manage the observability configuration for your Akka project
* link:akka_projects_observability_edit.html[akka projects observability edit]	 - Edit observability configuration for your Akka project.
* link:akka_projects_observability_export.html[akka projects observability export]	 - Exports an observability descriptor from the currently configured project.
* link:akka_projects_observability_get.html[akka projects observability get]	 - Get observability configuration for your Akka project.
* link:akka_projects_observability_set.html[akka projects observability set]	 - Set the observability settings for your Akka project
* link:akka_projects_observability_unset.html[akka projects observability unset]	 - Unset the observability settings for your Akka project

[discrete]

