= akka auth container-registry

Manage the Akka Container Registry configuration.

== Synopsis

The Akka Container Registry (ACR) can be used by all Akka users to deploy services and is available in all Akka regions.

== Options

----
  -h, --help   help for container-registry
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_auth.html[akka auth]	 - Manage Akka authentication.
* link:akka_auth_container-registry_clear-cached-token.html[akka auth container-registry clear-cached-token]	 - Clear the cached Akka Container Registry access token.
* link:akka_auth_container-registry_configure.html[akka auth container-registry configure]	 - Configure the Akka Container Registry docker credential helper.
* link:akka_auth_container-registry_credentials.html[akka auth container-registry credentials]	 - Retrieves an Akka Container Registry access token for the current user.
* link:akka_auth_container-registry_install-helper.html[akka auth container-registry install-helper]	 - Installs the Akka Docker credential helper in the selected directory.

[discrete]

