= akka

Akka control

== Synopsis

Welcome to the Akka CLI, for more information on its usage please visit the documentation https://doc.akka.io/index.html.

== Options

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -h, --help                help for akka
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_auth.html[akka auth]	 - Manage Akka authentication.
* link:akka_completion.html[akka completion]	 - Generate shell completion scripts
* link:akka_config.html[akka config]	 - Manage the local Akka configuration.
* link:akka_container-registry.html[akka container-registry]	 - Manage the Akka Container Registry.
* link:akka_docker.html[akka docker]	 - Manage Docker credentials for Akka projects.
* link:akka_docs.html[akka docs]	 - Opens the Akka documentation page
* link:akka_local.html[akka local]	 - Helps with local development.
* link:akka_logs.html[akka logs]	 - Display the last few lines of logs for a specific service.
* link:akka_organizations.html[akka organizations]	 - Manage your organizations on Akka
* link:akka_projects.html[akka projects]	 - Manage your Akka projects.
* link:akka_quickstart.html[akka quickstart]	 - Akka quickstart project samples.
* link:akka_regions.html[akka regions]	 - Manage regions on Akka
* link:akka_roles.html[akka roles]	 - Manage the user roles for an Akka project.
* link:akka_routes.html[akka routes]	 - Manage routes for your Akka project.
* link:akka_secrets.html[akka secrets]	 - Manage secrets for an Akka project.
* link:akka_services.html[akka services]	 - Manage and deploy services on Akka.
* link:akka_version.html[akka version]	 - Prints the akka version

[discrete]

