= akka container-registry

Manage the Akka Container Registry.

== Synopsis

The Kalix Container Registry (KCR) can be used by all Kalix users to deploy services and is available in all Kalix regions.

== Options

----
  -h, --help   help for container-registry
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka.html[akka]	 - Akka control
* link:akka_container-registry_delete-image.html[akka container-registry delete-image]	 - delete image from the Akka Container Registry.
If no tag is provided, it deletes all tags
* link:akka_container-registry_list.html[akka container-registry list]	 - List the Akka Container Registry and region.
* link:akka_container-registry_list-images.html[akka container-registry list-images]	 - list images from the Akka Container Registry.
* link:akka_container-registry_list-tags.html[akka container-registry list-tags]	 - list all images tags.
* link:akka_container-registry_print.html[akka container-registry print]	 - Print the path of the Akka Container Registry.
* link:akka_container-registry_push.html[akka container-registry push]	 - Push an Akka service image for a particular Akka project.

[discrete]

