= Process overview

include::ROOT:partial$include.adoc[]

The main steps in developing a service with Akka are:

. <<_create_a_project>>
. <<_specify_service_interface_and_domain_model>>
. <<_implement_components>>
. <<_endpoints>>
. <<_create_unit_tests>>
. <<_run_locally>>
. <<_package_service>>
. <<_deploy>>

[#_create_a_project]
== Create a project
All services and applications start as a Java project. Akka has a Maven archetype and plugin that makes this easier. You will code your service in this project. See xref:java:getting-started.adoc#[Getting started] for more details.

[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

Creating services in Akka follows the architecture outlined in xref:concepts:architecture-model.adoc#_architecture[Akka Architecture]. You start with your domain model, which models your business domain in plain old Java objects. Then you will create Akka components to coordinate them.

The main components of an Akka service are:

* Stateful xref:reference:glossary.adoc#entity[Entities]
* Stateful xref:reference:glossary.adoc#workflow[Workflows]
* xref:reference:glossary.adoc#view[Views], which return the state of multiple instances of a stateful entity.
* xref:reference:glossary.adoc#timed_action[Timed Actions]
* xref:reference:glossary.adoc#consumers[Consumers]

We recommend that you separate the service API and Entity domain data model. Separating the service interface and data model in different classes allows you to evolve them independently.

TIP: Kickstart a project using the xref:java:getting-started.adoc[Getting started] guide.

[#_implement_components]
== Implementing components

Stateful services can implement xref:java:key-value-entities.adoc[Key Value Entity] or xref:java:event-sourced-entities.adoc[Event Sourced Entity] and xref:java:views.adoc[View] components. Stateless services implement xref:reference:glossary.adoc#action[HTTP Endpoints]. Typically, a stateful service should only have one Entity type, but can also include Endpoints and Views.


=== Entities

Stateful services encapsulate business logic in Key Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.


TIP: To learn more about Akka entities see xref:java:key-value-entities.adoc[] and xref:java:event-sourced-entities.adoc[].

If you would like to update multiple Entities from a single request, you can compose that in the Endpoint, Consumer or Workflow.

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, which other services can consume. By defining your Consumer components, any service can expose their own events and consume events produced by other services or external systems.

=== Workflows

Akka Workflows are high-level descriptions to easily align business requirements with their implementation in code. Orchestration across multiple services with support for failure scenarios and compensating actions is simple with xref:java:workflows.adoc[Workflows].

=== Views

A View provides a way to retrieve state from multiple Entities based on a query. You can create views from Key Value Entity state, Event Sourced Entity events, and by subscribing to topics. For more information about writing views see xref:java:views.adoc[].

For more details and examples take a look at the following topics:

* xref:java:key-value-entities.adoc[Key Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:workflows.adoc[Workflows]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed Actions]
* xref:java:consuming-producing.adoc[]

[#_endpoints]
== Exposing components through Endpoints and Consumers
Endpoints are how you expose your services to the outside world. You use the xref:java:http-endpoints.adoc[HTTP endpoints] to do this.

They can also consume outside services and emit events for others to subscribe to. You use the xref:java:consuming-producing.adoc[Consumers] to do this.

[#_create_unit_tests]
== Testing your application

Writing automated tests for your application is a good practice. Automated testing helps catch bugs early in the development process, reduces the likelihood of regressions, enables confident refactoring, and ensures your application behaves as expected. There are three main types of tests to consider: unit tests, integration tests, and end-to-end tests.

=== Unit Tests

Unit tests focus on testing individual components in isolation to ensure they work as intended. The Akka SDK provides a test kit for unit testing your components.

=== Integration Tests

Integration tests validate the interactions between multiple components or services within your application, ensuring that different parts of your system work together as intended.

=== End-to-End Tests

End-to-end tests validate the entire application by simulating real-world user scenarios. These tests span multiple services or modules to ensure the system functions correctly as a whole, whether within the same project or across different projects. For example, you might test the data flow between two Akka services in the same project using service-to-service eventing. Akka also offers flexible configuration options to accommodate various environments.

[#_run_locally]
== Running locally

You can test and debug your services by xref:java:running-locally.adoc[running them locally] before deploying your _Service_. This gives you a local debug experience that is convenient and easy. 

[#_package_service]
== Package service

You use Docker to package your service and any of its dependencies for deployment. Distributing services as docker images makes Akka more cloud friendly and works well with containerization tools.

See xref:operations:container-registries.adoc[container registries] for more information.

[#_deploy]
== Deploy to akka.io

After testing locally, deploy your service to akka.io using the CLI or the Console. The following pages provide information about deployment:


* xref:operations:projects.adoc[Akka projects]
* xref:operations:deploy-service.adoc#_deploying_a_service[Deploying a packaged service]

== Next steps

Now that you have a project and have deployed it you should familairize yourself with operating an Akka project. See xref:operations:index.adoc[] for more information about operating Akka services.

The following topics may also be of interest.

- xref:best-practices.adoc[Best practices]
