= Process overview

include::ROOT:partial$include.adoc[]

The main steps in developing a service with Akka are:

. <<_create_a_project>>
. <<_specify_service_interface_and_domain_model>>
. <<_implement_components>>
. <<_endpoints>>
. <<_create_unit_tests>>
. <<_run_locally>>
. <<_package_service>>
. <<_deploy>>

[#_create_a_project]
== Create a project
All services and applications start as a Java project. Akka has a Maven archetype and plugin that makes this easier. You will code your service in this project. See xref:java:getting-started.adoc#[Getting started] for more details.

[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

Creating services in Akka follows the architecture outlined in xref:concepts/programming-model.adoc#_Architecture[Akka Architecture]. You start with your domain model, which models your business domain in plain old Java objects. Then you will create Akka components to coordinate them.

The main components of an Akka service are:

* Stateful xref:reference:glossary.adoc#entity[Entities]
* Stateful xref:reference:glossary.adoc#Workflow[Workflows]
* xref:reference:glossary.html#view[Views], which return the state of multiple instances of a stateful entity.
* xref:reference:glossary.adoc#timed_action[Timed Actions]
* xref:reference:glossary.adoc#consumers[Consumers]

We recommend that you separate the service API and Entity domain data model. Separating the service interface and data model in different classes allows you to evolve them independently.

TIP: Kickstart a project using the xref:java:getting-started.adoc[Getting started] guide.

[#_implement_components]
== Implementing components

Stateful services can implement xref:java:key-value-entities.adoc[Key Value Entity] or xref:java:event-sourced-entities.adoc[Event Sourced Entity] and xref:java:views.adoc[View] components. Stateless services implement xref:reference:glossary.adoc#action[HTTP Endpoints]. Typically, a stateful service should only have one Entity type, but can also include Endpoints and Views.


=== Entities

Stateful services encapsulate business logic in Key Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.


TIP: To learn more about Kalix entities see xref:java:key-value-entities.adoc[Implementing Key Value Entities] and xref:java:event-sourced-entities.adoc[Implementing Event Sourced Entities].

If you would like to update multiple Entities from a single command, you can use forwarding and side effects.

TIP: For more information see xref:java:http-endpoints.adoc#_advanced_http_requests_and_responses[HTTP Endpoints as Controllers].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

=== Workflows

Akka Workflows are high-level descriptions to easily align business requirements with their implementation in code. Orchestration across multiple services with support for failure scenarios and compensating actions is simple with xref:java:workflows.adoc[Workflows].

=== Views

A View provides a way to retrieve state from multiple Entities based on a query. You can create views from Key Value Entity state, Event Sourced Entity events, and by subscribing to topics. For more information about writing views see xref:java:views.adoc[Implementing Views].

For more details and examples take a look at the following topics:

* xref:java:key-value-entities.adoc[Key Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:workflows.adoc[Workflows]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed Actions]
* xref:java:consuming-producing.adoc[]

[#_endpoints]
== Exposing components through Endpoints
Endpoints are how you expose your services to the outside world. They can also consume outside services and emit events for others to subscribe to. You use the xref:java:http-endpoints.adoc[HTTP endpoints] to do this.

[#_create_unit_tests]
== Testing your application

It is good practice to write unit tests and integration tests as you implement your services.

The Akka SDK provides a test kit dependency that you can use to write unit tests for Entities as well as integration tests. Please consult the component specific pages to learn more about writing unit tests and integration tests for your application.


[#_run_locally]
== Running locally

You can test and debug your services by xref:java:running-locally.adoc[running them locally] before deploying your _Service_. This gives you a local debug experience that is convenient and easy. 

[#_package_service]
== Package service

You use Docker to package your service and any of its dependencies for deployment. Distributing services as docker images makes Akka more cloud friendly and works well with containerization tools.

See xref:operations:container-registries.adoc[container registries] for more information.

[#_deploy]
== Deploy to akka.io

After testing locally, deploy your service to akka.io using the CLI or the Console. The following pages provide information about deployment:


* xref:operations:projects.adoc[Akka projects]
* xref:operations:deploy-service.adoc#_deploy[Deploying a packaged service]
