= Access Control Lists (ACLs)

The simplest access control that the Akka offers is through Access Control Lists (ACLs). ACLs allow you to
specify lists of what can access your services, at multiple granularity. For example, you can configure a method that
initiates a payment on a payment service to only accept requests from the shopping cart service. You can also control
whether services or methods can be invoked from the Internet.

==  Principals

A principal in Akka is an abstract concept that represents anything that can make or be the source of a request.
Principals that are currently supported by Akka include other services, and the internet. Akka uses mTLS support to
associate requests with one or more principals.

Note that requests that have the internet principal are requests that Akka has identified as coming through the Akka
ingress route. This is identified by mTLS, however it does not imply that mTLS has been
used to connect to the ingress from the client in the internet. These are separate hops. To configure mTLS from
internet clients, see https://docs.kalix.io/security/tls-certificates.html[TLS certificates].

== Configuring ACLs

Akka SDK ACLs consist of two lists of principal matchers. One to allow to invoke a method, and the other to deny to
invoke a method. For a request to be allowed, at least one principal associated with a request must be matched by at
least one principal matcher in the allow list, and no principals associated with the request may match any principal
matchers in the deny list.

An ACL can be configured at the class level, or at the method level. If an ACL is configured at the class level it
applies to all methods in the class. Unless it's overridden by an ACL added at method level.

Here is an example of an ACL added at the class level on a Http Endpoint:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tags=endpoint-class;class-level-acl]
----

The above ACL only allows incoming traffic from `service-a`. This rule is applied to all methods in this Http Endpoint.

This rule can be overridden by an ACL on a method level. Here is an example ACL on a method that overrides the class level ACL:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tags=endpoint-class;class-level-acl;method-overwrite]
----
Note that an ACL defined on a method completely overrides an ACL defined at class level. It does not add to
it.

You can combine `allow` and `deny` rules. In the following example, access is open to all other services, except
`service-b`.

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tag=allow-deny]
----

To allow all traffic:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tag=all-traffic]
----

To allow only traffic from the internet:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tag=internet]
----

To allow traffic from `service-a` and `service-b`:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tag=multiple-services]
----

To block all traffic, an ACL with no allows can be configured:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tag=block-traffic]
----


== Default ACL

If no ACLs are defined at all, Akka will deny requests from both other services and the internet to all components of
an Akka service.

IMPORTANT: The Maven archetype includes an example endpoint with a very permissive ACL that opens access to public
internet
requests. This allows for easy try out and testing. For production usage, make sure to add appropriate ACL
restrictions.

=== Customizing the deny code

When a request is denied, by default a 403 `Forbbiden`, is sent. The code that is returned when a request is denied can be customised using the `deny_code` property.

For example, to make Akka reply with 404, `Not Found`:

[source, java, indent=0]
----
include::example$doc-snippets/src/main/java/com/example/acl/UserEndpoint.java[tags=endpoint-class;deny-class-level]
----

Similar to allow and deny rules, deny codes defined at class level are applied to all methods in the component, but
can be overwritten on a per method base.

== Backoffice and self invocations

Invocations of methods from the same service, or from the backoffice using the `akka services proxy` command, are always
permitted, regardless of what ACLs are defined on them.

== Local development with ACLs

When testing or running in development, by default, all calls to your service will be blocked as ACLs are enabled by default.

You can disable the local ACL checks by configuring the following settings in the `application.conf` file:

[source,conf]
.src/main/resources/application.conf
----
akka.javasdk.dev-mode.acl.enabled = false
----

Alternativly, start with:

[source,shell]
----
mvn compile exec:java -Dakka.javasdk.dev-mode.acl.enabled=false
----

ifdef::todo[TODO: Impersonate-Akka-Service should translate to Impersonate-Kalix-Service internally]

ifdef::todo[TODO: Http Client should add Impersonate-Akka-Service header when in dev-mode]


== Programmatically accessing principals

The current principal associated with a request can be accessed by reading metadata headers. If the request came from
another service, the `_kalix-src-svc` header will be set to the name of the service that made the request. Akka
guarantees that this header will only be present from an authenticated principal, it can't be spoofed.

For internet, self and backoffice requests, the `_kalix-src` header will be set to `internet`, `self` and
`backoffice` respectively. Backoffice requests are those made using the `akka services proxy` command,
they are authenticated and authorized to ensure only developers of your project can make them.


ifdef::todo[TODO: what to do with _kalix vs. _akka headers?]

ifdef::todo[TODO: we need to make headers more accessible in Endpoint or maybe an Endpoint Context?]

== Inspecting the principal inside a service

Checking the ACLs are in general done for you by Akka, however in some cases programmatic access to the principal of a
call can be useful.

Accessing the principal of a call inside a service is possible through the request metadata `Metadata.principals()`.
The `Metadata` for a call is available through the context (`CommandContext`) of the component.

ifdef::todo[TODO: how to access it from inside a HttpEndpoint?]

== ACLs when running unit tests

In the generated unit test testkits, the ACLs are ignored.

== ACLs when running integration tests

ACLs are enabled by default when running integration tests.

ACL rules will be applied whenever a call is made using testkit's `HttpClient`. Those calls are interpreted as
originating from the internet. You can disable the ACL checks by overriding the `testKitSettings()` method.

[source, java, indent=0]
----
include::example$doc-snippets/src/it/java/com/example/acl/UserEndpointIntegrationTest.java[tag=disable-acl-in-it]
----

Calls made through the `ComponentClient` are internal to the service and therefore no ACL rule is applied.