= Build your first application

include::ROOT:partial$include.adoc[]

This guide will walk you through the process of setting up your environment, generating a project, and implementing a simple application. By the end, you will have a functional Shopping Cart application built with the Akka SDK.

== Overview

The Akka SDK comes with Maven support that enables you to get started quickly. In this guide, you will:

* Use the Akka Maven archetype to generate a skeleton project that follows the recommended onion architecture.
* Understand how to use the Akka Maven parent POM to define dependencies and run your application locally.

== Prerequisites

include::ROOT:partial$cloud-dev-prerequisites.adoc[]


== Generate and build the skeleton project

The Maven archetype template prompts you to specify the project's group ID, name and version interactively. Run it using the commands shown for your OS.

[sidebar]
In IntelliJ, you can skip the command line. Open the IDE, select
*File > New > Project*, and click to activate *Create from archetype*. Use the UI to locate the archetype and fill in the blanks.

Follow these steps to generate and build your project:

. From a command window, run the template in a convenient location:
+
[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--

. Fill in
* groupId: `com.example`
* artifactId: `shoppingcart`
* version: `1.0-SNAPSHOT`
* package: `shoppingcart`

. Navigate to the new project directory.

. Open it in your preferred IDE / Editor.

== Implementing first component

Akka has different kinds of components that you can use to implement your application.
The list of components are:

* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:key-value-entities.adoc[Key Value Entities]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed Actions]
* xref:java:consuming-producing.adoc[Consumers]

For this *Getting started* walk-through, we will implement a Shopping Cart based on an Event Sourced Entity.

Through our "Shopping Cart" Event Sourced Entity we expect to manage our cart, adding and removing items as we please. Being event-sourced means it will represent changes to state as a series of domain events. Let’s have a look at what kind of model we expect to store and the events our entity might generate.

=== Define the domain model

First, define the domain class `ShoppingCart` in package `shoppingcart.domain` with some basic business logic.

[source,java,indent=0]
.{sample-base-url}/shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[ShoppingCart.java]
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[tags=top;domain]
----

Add an interface `ShoppingCartEvent` with the domain events in package `shoppingcart.domain`.

[source,java,indent=0]
.{sample-base-url}/shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCartEvent.java[ShoppingCartEvent.java]
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCartEvent.java[tags=top;domain]
----

=== Define the entity

The Event Sourced Entity is defined in the `ShoppingCartEntity`.

Create a class named `ShoppingCartEntity` in package `shoppingcart.application`.

[source,java,indent=0]
.{sample-base-url}/shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[ShoppingCartEntity.java]
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tags=top;class;getCart;addItem]
----

=== Define the external API

The `Shopping Cart` API is defined by the `ShoppingCartEndpoint`.

Create a class named `ShoppingCartEndpoint` in package `shoppingcart.api`.


[source,java,indent=0]
.{sample-base-url}/shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java[ShoppingCartEndpoint.java]
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java[tags=top;class;get;addItem]
----

== Run locally

To start your service locally, run:

[source,bash]
----
mvn compile exec:java
----

This command will start your Akka service.

Once successfully started, any defined endpoints should be available at `localhost:9000`.

You can try sending a request using https://curl.se[curl], a minimal command line HTTP client.

Add an item:

[source, command window]
----
curl -i -XPUT -H "Content-Type: application/json" localhost:9000/carts/123/item -d '
{"productId":"akka-tshirt", "name":"Akka Tshirt", "quantity": 10}'
----

Get cart state:

[source, command window]
----
curl localhost:9000/carts/123
----

== Deploy to akka.io

ifdef::todo[TODO: should it be here, or only in the developent-process page or where?]

Deploy your service following the instructions at xref:concepts:development-process.adoc#_deploy[Development Process - Deploy to Akka].

== Download full sample

You can download the full source code of the Shopping Cart sample as a link:_attachments/shopping-cart-quickstart.zip[zip file].
