= Implementing Event Sourced Entities
:sample-url: https://github.com/lightbend/akka-javasdk/tree/main/samples/shopping-cart-quickstart

include::ROOT:partial$include.adoc[]

:TODO: add illustrations from the local console

Event Sourced Entities persist their state with https://en.wikipedia.org/wiki/ACID[ACID semantics{tab-icon}, window="new"], scale horizontally, and isolate failures. They use the Event Sourcing Model--instead of persisting the current state, they persist all the events that led to the current state. Akka stores these events in a https://docs.kalix.io/reference/glossary.html#journal[journal].

An Event Sourced Entity must not update its in-memory state directly as a result of a https://docs.kalix.io/reference/glossary.html#command[_command_]. The handling of a command, if it results in changes being required to state, should persist https://docs.kalix.io/reference/glossary.html#event[_events_]. These events will then be processed by the entity, at which point the in-memory state can and should be changed in response.

When you need to read state in your service, ask yourself _what events should I be listening to_?. When you need to write state, ask yourself _what events should I be persisting_?

ifdef::todo[TODO: add an illustration]

To load an Entity, Akka reads the journal and replays events to compute the Entity's current state. As an optimization, by default, Event Sourced Entities persist state snapshots periodically. This allows Akka to recreate an Entity from the most recent snapshot plus any events saved after the snapshot.

In contrast with typical create, read, update (CRUD) systems, event sourcing allows the state of the Entity to be reliably replicated to other services. Event Sourced Entities use offset tracking in the journal to record which portions of the system have replicated which events.

include::partial$entity-sharding.adoc[]

:TODO: TIP: To learn more about event sourcing, check out the free Lightbend Academy course, https://academy.lightbend.com/courses/course-v1:lightbend+LRA-CQRSandEventSourcing+v1/about[Reactive Architecture: CQRS & Event Sourcing {tab-icon}, window="new"].

https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entities] persist changes as events and snapshots. Akka needs to serialize that data to send it to the underlying data store. However, we recommend that you do not persist your service's public API messages. Persisting private API messages may introduce some overhead when converting from a public message to an internal one but it allows the logic of the service public interface to evolve independently of the data storage format, which should be private.

The steps necessary to implement an Event Sourced Entity include:

. Model the entity's state and its domain events.
. Implementing behavior in command and event handlers.

The following sections walk through these steps using a shopping cart service as an example (working sample available {sample-url}[here {tab-icon}, window="new"]).

== Modeling the Entity

Through our "Shopping Cart" Event Sourced Entity we expect to manage our cart, adding and removing items as we please. Being event-sourced means it will represent changes to state as a series of domain events. So let's have a look at what kind of model we expect to store and the events our entity might generate.

[source,java]
.src/main/java/shoppingcart/domain/ShoppingCart.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[tag=domain]
----
<1> Our `ShoppingCart` is fairly simple, being composed only by a `cartId` and a list of line items.
<2> A `LineItem` represents a single product and the quantity we intend to buy.

NOTE: Above we are taking advantage of the Java `record` to reduce the amount of boilerplate code, but you can use regular classes so long as they can be serialized to JSON (e.g. using Jackson annotations).

Another fundamental aspect of our entity will be its domain events. For now, we will have 3 different events `ItemAdded`, `ItemRemoved` and `CheckedOut`, defined as below:

[source,java]
.src/main/java/shoppingcart/domain/ShoppingCartEvent.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCartEvent.java[tag=events]
----
<1> The 3 types of event all derive from the same type `ShoppingCartEvent`.
<2> Includes the logical type name using `@TypeName` annotation.

IMPORTANT: The use of logical names for subtypes is essential for maintainability purposes. Our recommendation is to use logical names (i.e. `@TypeName`) that are unique per Akka service. Check xref:serialization.adoc#_type_name[type name] documentation for more details.

include::partial$entity-ids.adoc[]

== Event Sourced Entity's Effect API

The Event Sourced Entity's Effect defines the operations that Akka should perform when an incoming command is handled by an Event Sourced Entity.

An Event Sourced Entity Effect can either:

* persist events and send a reply to the caller
* directly reply to the caller if the command is not requesting any state change
* instruct Akka to delete the entity
* return an error message

== Implementing behavior

Now that we have our Entity state defined along with its events, the remaining steps can be summarized as follows:

- declare your entity and pick a component id (it needs to be unique as it will be used for sharding purposes);
- implement how each command is handled and which event(s) it generates;
- provide an event handler and how it updates the entity's state.

The class signature for our shopping cart entity will look like this:

[source,java]
.src/main/java/shoppingcart/domain/application/ShoppingCartEntity.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=class]
----
<1> Create a class that extends `EventSourcedEntity<S, E>`, where `S` is the state type this entity will store (i.e. `ShoppingCart`) and `E` is the top type for the events it persists (i.e. `ShoppingCartEvent`).
<2> Make sure to annotate such class with `@ComponentId` and pass a stable unique identifier for this entity type.


NOTE: The `@ComponentId` value `shopping-cart` is common for all instances of this entity but must be stable - cannot be changed after a production deploy - and unique across the different entity types in the service.

=== Updating state

Having created the basis of our entity, we will now define how each command is handled. In the example below, we define a method that will add a new line item to a given shopping cart. It returns an `Effect` to persist an event and then sends a reply once the event is stored successfully. The state is updated by the event handler.

IMPORTANT: The **only** way for a command handler to modify the Entity's state is by persisting an event. Any modifications made directly to the state (or instance variables) from the command handler are not persisted. When the Entity is passivated and reloaded, those modifications will not be present.

[source,java,indent=0]
.src/main/java/shoppingcart/application/ShoppingCartEntity.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=addItem]
----
<1> The validation ensures the quantity of items added is greater than zero and it fails for calls with illegal values by returning an `Effect` with `effects().error`.
<2> From the current incoming `LineItem` we create a new `ItemAdded` event representing the change of the cart.
<3> We store the event by returning an `Effect` with `effects().persist`.
<4> The acknowledgment that the command was successfully processed is only sent if the event was successfully stored and applied, otherwise there will be an error reply. The lambda parameter `newState` gives us access to the new state returned by applying such event.
<5> Event handler returns the updated state after applying the event - the logic for state transition is defined inside the `ShoppingCart` domain model.

As mentioned above, the business logic that allows us to transition between states was placed on the domain model as seen below:

[source,java,indent=0]
.src/main/java/shoppingcart/domain/ShoppingCart.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[tag=itemAdded]
----
<1> For an existing item, we will make sure to sum the existing quantity with the incoming one.
<2> Returns an update list of items without the existing item.
<3> Adds the update item to the shopping cart.
<4> Returns a new instance of the shopping cart with the updated line items.


=== Retrieving state

To have access to the current state of the entity we can use `currentState()` as you have probably noticed from the examples above. However, what if this is the first command we are receiving for this entity? The following example shows the implementation of the read-only command handler `getCart`:

[source,java,indent=0]
.src/main/java/shoppingcart/application/ShoppingCartEntity.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=getCart]
----
<1> Stores the `entityId` on an internal attribute so we can use it later.
<2> Provides initial state - overriding `emptyState()` is optional but if not doing it, be careful to deal with a currentState() with a `null` value when receiving the first command or event.
<3> Returns the current state as reply for the request.

IMPORTANT: We are returning the internal state directly back to the requester. In the endpoint, it's usually best to convert this internal domain model into a public model so the internal representation is free to evolve without breaking clients code.

== Snapshots

Snapshots are an important optimization for Event Sourced Entities that persist many events. Rather than reading the entire journal upon loading or restart, Akka can initiate them from a snapshot.

Snapshots are stored and handled automatically by Akka without any specific code required. Snapshots are stored after a configured number of events:

[source,conf,indent=0]
.src/main/resources/application.conf
----
include::example$shopping-cart-quickstart/src/main/resources/application.conf[tag=snapshot-every]
----

When the Event Sourced Entity is loaded again, the snapshot will be loaded before any other events are received.

== Deleting an Entity

Normally, Event Sourced Entities are not deleted because the history of the events typically provide business value.
For certain use cases or for regulatory reasons the entity can be deleted.

[source,java,indent=0]
.src/main/java/shoppingcart/application/ShoppingCartEntity.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=checkout]
----
<1> Persist final event before deletion, which is handled as any other event.
<2> Instruction to delete the entity.

When you give the instruction to delete the entity it will still exist for some time, including its events and snapshots. The actual removal of events and snapshots will be deleted later to give downstream consumers time to process all prior events, including the final event that was persisted together with the `deleteEntity` effect. By default, the existence of the entity is completely cleaned up after a week.

It is not allowed to persist more events after the entity has been "marked" as deleted. You can still handle read requests to the entity until it has been completely removed.

It is best to not reuse the same entity id after deletion, but if that happens after the entity has been completely removed it will be instantiated as a completely new entity without any knowledge of previous state.

Note that xref:views.adoc#ve_delete[deleting View state] must be handled explicitly.

== Multi-region replication

Event Sourced Entities can be replicated to other regions. This is useful for several reasons:

* resilience to tolerate failures in one location and still be operational, even multi-cloud redundancy
* possibility to serve requests from a location near the user to provide better responsiveness
* load balancing to be able to handle high throughput

For each entity there is a primary region, which handles all write requests. Read requests can be served from any region.

Read requests are defined by declaring the command handler method with `ReadOnlyEffect` as return type. A read-only handler cannot persist events, and that is enforced at compile time.

[source,java,indent=0]
.src//main/java/shoppingcart/application/ShoppingCartEntity.java
----
include::example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=read-only]
----

Write requests are defined by declaring the command handler method with `Effect` as return type, instead of `ReadOnlyEffect`. Write requests are routed to the primary region and handled by the entity in that region even if the original call to the entity with the component client was made from another region.

Events persisted by the entity in the primary region are replicated to other regions and processed by corresponding entities there. This means that the state of the entities in all regions are updated from the events of the primary.

The replication is asynchronous, which means that read replicas are eventually updated. Normally within a few milliseconds, but if there is for example a problem with the network between the regions it can take longer time for the read replicas to become up to date, but eventually they will.

This also means that you might not see your own writes, immediately. Consider the following:

* send a write request and that is routed to a primary in another region
* after receiving the response of the write request, you send a read request that is served by the non-primary region
* the entity in the non-primary region might not have seen the replicated events for the update yet, and therefore replies with "stale" information

If it's important for some read requests to have seen latest writes you can use `Effect` for such command handler, even though it is not persisting any events. Then the request will be routed to the primary and use the latest fully consistent state.

=== Selecting primary

There are two operational choices for deciding where the primary is located:

* static mode - one region is defined as the primary when deploying the service, and all entities will use that region as primary
* dynamic mode - the primary is selected by each individual entity based on where the first event is persisted

The replication mode is defined when deploying the service.

ifdef::todo[TODO: link to ops docs for multi-region deployments]

When using the dynamic mode the application must make sure that a specific entity is not created concurrently in more than one region. Events will still be replicated if that happens but there are no ordering guarantees of these initial events, which could result in conflicting state in different regions. After the initial events have been replicated, one single primary is selected also in this case.

It is possible to switch between static and dynamic mode, but this should only be done with careful consideration of the consequences. For example, when changing the primary, not all events may have been replicated and the new primary may not be fully up to date. This is why there is a third mode. This is a read-only mode for all regions, which causes all write requests to be rejected. This can be used as an intermediate stage to ensure that all events have been replicated before the primary is changed.

== Side Effects

An entity doesn't perform any external side effects aside from persisting events and replying to the request. Side effects can be handled from the Workflow, Consumer, or Endpoint components that are calling the entity.

== Testing the Entity

include::partial$testing-entity.adoc[]


=== Unit tests

The following snippet shows how the `EventSourcedTestKit` is used to test the `ShoppingCartEntity` implementation. Akka provides two main APIs for unit tests, the `EventSourcedTestKit` and the `EventSourcedResult`. The former gives us the overall state of the entity and all the events produced by all the calls to the Entity. While the latter only holds the effects produced for each individual call to the Entity.

.src/test/java/shoppingcart/application/ShoppingCartTest.java
[source,java]
----
include::example$shopping-cart-quickstart/src/test/java/shoppingcart/application/ShoppingCartTest.java[]
----
<1> Creates the TestKit passing the constructor of the Entity.
<2> Calls the method `addItem` from the Entity in the `EventSourcedTestKit` with quantity `10`.
<3> Asserts the return value is `"OK"`.
<4> Returns the next event of type `IdemAdded` and asserts on the quantity.
<5> Add a new item with quantity `5`.
<6> Asserts that the total number of events should be 2.
<7> Calls the `getCart` method and asserts that quantity should be `15`.

NOTE: The `EventSourcedTestKit` is stateful, and it holds the state of a single entity instance in memory. If you want to test more than one entity in a test, you need to create multiple instance of `EventSourcedTestKit`.

*EventSourcedResult*

Calling a command handler through the TestKit gives us back an link:{attachmentsdir}/testkit/akka/javasdk/testkit/EventSourcedResult.html[`EventSourcedResult` {tab-icon}, window="new"]. This class has methods that we can use to assert the handling of the command, such as:

* `getReply()` - the response from the command handler if there was one, if not an, exception is thrown, failing the test.
* `getAllEvents()` - all the events persisted by handling the command.
* `getState()` - the state of the entity after applying any events the command handler persisted.
* `getNextEventOfType(ExpectedEvent.class)` - check the next of the persisted events against an event type, return it for inspection if it matches, or fail the test if it does not. The event gets consumed once is inspected and the next call will look for a subsequent event.

*EventSourcedTestKit*

For the above example, this class provides access to all the command handlers of the `ShoppingCart` entity for unit testing. In addition to that also has the following methods:

* `getState()` - the current state of the entity, it is updated on each method call persisting events.
* `getAllEvents()` - all events persisted since the creation of the testkit instance.


=== Integration tests

The skeleton of an Integration Test is generated for you if you use the archetype to start your Akka service. Let's see what it could look like to test our `ShoppingCartEntity`:

./src/it/java/shoppingcart/IntegrationTest.java
[source,java,indent=0]
----
include::example$shopping-cart-quickstart/src/it/java/shoppingcart/IntegrationTest.java[tag=sample-it]
----
<1> Note the test class must extend `TestKitSupport`.
<2> A built-in component client is provided to interact with the components.
<3> Request to create a new shopping cart with id `cart-abc`.
<4> Request to add an item to the cart.
<5> Request to retrieve current status of the shopping cart.
<6> Assert there should only be one item.

NOTE: The integration tests in samples are under a specific project profile `it` and can be run using `mvn verify -Pit`.

== Exposing entities directly

include::partial$component-endpoint.adoc[]

=== API

The entity is exposed at a fixed path:

[source]
----
/akka/v1.0/entity/<component id>/<entity id>/<method>
----

In our shopping cart example that is:

[source,shell]
----
curl localhost:9000/akka/v1.0/entity/shopping-cart/12345/getCart
----

or, to add an item:

[source,shell]
----
curl localhost:9000/akka/v1.0/entity/shopping-cart/12345/addItem \
  --header "Content-Type: application/json" \
  -XPOST \
  --data '{"productId":"akka-tshirt","name":"Akka Tshirt","quantity":10}'
----
