= Getting started with the Akka SDK

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Akka SDK comes with Maven support that gets you started quickly:

* The Akka *Maven archetype* generates a skeleton project with the project structure, following the onion architecture recommendation. The generated project also contains configuration for packaging and deploying the service.

* The Akka *Maven plugin* to helps you run your application locally and deploy it to akka.io.

== Prerequisites

* An https://console.akka.io/register[Akka account]
* https://adoptium.net/marketplace/[Eclipse Temurin] or Red Hat Enterprise Linux build of OpenJDK{java-version}
* https://maven.apache.org/install.html[Apache Maven] version {minimum_maven_version} or later
* https://docs.docker.com/get-started/get-docker/[Docker] {minimum_docker_version} or later

:sectnums:

== Generate and build the skeleton project

The Maven archetype template prompts you to specify the project's group ID, name and version interactively. Run it using the commands shown for your OS.

[sidebar]
In IntelliJ, you can skip the command line. Open the IDE, select
*File > New > Project*, and click to activate *Create from archetype*. Use the UI to locate the archetype and fill in the blanks.

Follow these steps to generate and build your project:

. From a command window, run the template in a convenient location:
+
[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--

. Navigate to the new project directory.

. Open it on your preferred IDE / Editor.

== Examine the project

== Implementing first component

Akka has different kinds of components that you can use to implement your application.
The list of components are:

* xref:java:key-value-entities.adoc[Key Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed Actions]
* xref:java:consuming-producing.adoc[Consumers]

For this *Getting started* walk-through, we will implement a Counter based on a Key Value Entity. It's a simple counter
that receives commands to increase the counter.

.src/main/java/com/example/application/CounterEntity.java
[source,java]
----
include::example$key-value-counter/src/main/java/com/example/application/CounterEntity.java[tags=declarations]
----
<1> Every Entity must be annotated with `@ComponentId` with a stable unique identifier for this entity type.
<2> The `CounterEntity` class should extend `akka.javasdk.keyvalueentity.KeyValueEntity`.
<3> The initial state of each counter is defined with value 0.

Akka will automatically find annotated components annotated with `@ComponentId` and make them available for use in your application.

We can now add further commands to allowing for modifying the counter:

.src/main/java/com/example/application/CounterEntity.java
[source,java,indent=0]
----
include::example$key-value-counter/src/main/java/com/example/application/CounterEntity.java[tags=behaviour]
----
<1> Set the new counter value to the value received from the command request.
<2> Reply with the new counter value wrapped within a `Counter` object.
<3> `plusOne` increases the counter by adding 1 to the current state.
<4> Finally, using the Effect API, you instruct Akka to persist the new state, and build a reply with the wrapper object.

The project also includes a dependency on the *Kalix Java SDK Test Kit*. Please consult the specific documentation page
for each type of component to learn more about writing unit tests and integration tests for your application.

== Package service

The project is configured to package your service into a Docker image which can be deployed to Akka. The Docker image
name can be changed in the `pom.xml` file's `properties` section. Update this file to publish your image to your Docker repository.

The built docker image is minimal and only contains the service itself and the SDK and transitive dependencies. In a deployment
environment it is combined with a runtime image which contains a JVM and the runtime to actually run.

[source,bash]
----
mvn install
----

TIP: For more details see xref:concepts:development-process.adoc#_package_service[Development Process - Package service].

== Run locally

To start your service locally, run:

[source,bash]
----
mvn compile exec:java
----

This command will start your Akka service.

Once successfully started, any defined endpoints should be available at `localhost:9000`.

You can try sending a request using https://curl.se[curl], a minimal command line HTTP client:

[source, command window]
----
curl -XPOST -H "Content-Type: application/json" localhost:9000/counter/foo/increase -d '{ "value": 10 }'
----

== Deploy to akka.io

FIXME should it be here, or only in the developent-process page or where?

Deploy your service following the instructions at xref:concepts:development-process.adoc#_deploy[Development Process - Deploy to Akka].
