= Getting started with the Akka SDK

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Akka SDK comes with Maven support that gets you started quickly:

* The Akka *Maven archetype* generates a skeleton project with the project structure, following the onion architecture recommendation. The generated project also contains configuration for packaging and deploying the service.

* The Akka *Maven plugin* to helps you run your application locally and deploy it to akka.io.

== Prerequisites

Before you start, make sure you have the following:

* Java {java-version} or later
* Apache Maven {minimum_maven_version} or later

:sectnums:

== Generate and build the skeleton project

The Maven archetype template prompts you to specify the project's group ID, name and version interactively. Run it using the commands shown for your OS.

[sidebar]
In IntelliJ, you can skip the command line. Open the IDE, select
*File > New > Project*, and click to activate *Create from archetype*. Use the UI to locate the archetype and fill in the blanks.

Follow these steps to generate and build your project:

. From a command window, run the template in a convenient location:
+
[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--

. Navigate to the new project directory.

. Open it on your preferred IDE / Editor.

== Examine the project

:TODO: Adapt once we have the new archetype

== Implementing first component

Kalix have different kinds of components that you can use to implement your application.
The list of components are:

* xref:java:key-value-entities.adoc[Key Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:views.adoc[Views]
* xref:java:timed-actions.adoc[Timed Actions]
* xref:java:consuming-producing.adoc[Consumers]

For this *Getting started* walk-through, we will implement a Counter based on a Key Value Entity. It's a simple counter
that receives commands to increase the counter.

.src/main/java/com/example/application/CounterEntity.java
[source,java]
----
include::example$valueentity-counter/src/main/java/com/example/application/CounterEntity.java[tags=declarations;increase;close]
----
<1> Every Entity must be annotated with `@ComponentId` with a stable identifier. This identifier should be unique among the different existing entities within a Kalix application.
<2> The `@Id` value should be unique per entity and map to some field being received on the route path, in this example it's the `counter_id`.
<3> The `CounterEntity` class should extend `kalix.javasdk.valueentity.ValueEntity`.
<4> The initial state of each counter is defined as 0.
<5> The method is accessible as a POST endpoint on `/counter/\{counter_id\}/increase`, where `counter_id` will be its unique identifier.
Note that it matches the `@Id` value.
<6> Its `increaseBy` method receives a `Number` as input and increases the counter by adding it to the current state.
<7> Finally, using the Effect API, we instruct Kalix to persist the new state, and we build a reply.

The `Counter` record in this example is used as input for the `increment` method and as to return the
counter's current state.

.src/main/java/com/example/domain/Counter.java
[source,java]
----
include::example$valueentity-counter/src/main/java/com/example/domain/Counter.java[]
----

[sidebar]
An Akka component doesn't require any other annotation. They will be registered to Akka and be exposed automatically.
It suffices to add them on the same package or on a sub-package of your `Main` class.

The project also includes a dependency on the *Kalix Java SDK Test Kit*. Please consult the component specific pages to
learn more about writing unit tests and integration tests for your application.

== Package service

The project is configured to package your service into a Docker image which can be deployed to Kalix. The Docker image
name can be changed in the `pom.xml` file's `properties` section. Update this file to publish your image to your Docker repository.

This uses JDK {java-version} and the image is based on the link:https://adoptium.net/[Eclipse Adoptium] JDK image (formerly Adopt OpenJDK). Choose a different image in the `docker-maven-plugin` configuration  `pom.xml` file.

[source,bash]
----
mvn install
----

TIP: For more details see xref:concepts:development-process.adoc#_package_service[Development Process - Package service].

== Run locally

To start your service locally, run:

[source,bash]
----
mvn compile exec:java
----

This command will start your Kalix service and a companion Kalix Runtime as configured in `docker-compose.yml` file.

If you prefer, you can also start docker-compose directly by running `docker-compose up` in one terminal and in another terminal start your Kalix service with:

[source,bash]
----
mvn kalix:run
----

With both the runtime and your service running, any defined endpoints should be available at `localhost:9000`,
the runtime local address.

[source, command window]
----
curl -XPOST -H "Content-Type: application/json" localhost:9000/counter/foo/increase -d '{ "value": 10 }'
----

== Deploy to Kalix

To deploy your service to Kalix:

First make sure you have updated the `dockerImage` property in the `pom.xml` to point at your Docker registry.
Then use the `deploy` target to build the container image, publish it to the container registry as configured in the `pom.xml` file, and the target `kalix:deploy` to automatically deploy the service to Kalix:

[source,command line]
----
mvn deploy kalix:deploy
----
include::partial$important-mvn-kalixdeploy.adoc[]

- When using the CLI, in your command window, you can set your Kalix project to be the current project:

+
[source, command window]
----
kalix config set project <project-name>
----

- Deploy your service following the instructions at xref:concepts:development-process.adoc#_deploy_to_kalix[Development Process - Deploy to Akka].
