= Developing

include::ROOT:partial$include.adoc[]

The Akka SDK provides you proven design patterns that enable your apps to remain responsive to change. It frees you from infrastructure concerns and lets you focus on the application logic.

With its few, concise components, the Akka SDK is easy to learn, and you can develop services in quick, iterative steps by running your code locally with full insight through Akka's console.

Akka services let you build REST endpoints with flexible access control and multiple ways to expose these endpoints to their consuming systems or applications. Akka is secure by default, and you explicitly express the desired access through code and configuration.

Akka encapsulates data together with the logic to access and modify it. The data itself is expressed in regular Java records (plain old Java objects). The same goes for the events that change the data, these are expressed in pure Java to reflect business events that lead to data updates. Akka enables you to build fully event-driven services by combining logic and data into one thing: entities.

Data and changes to it are managed by Akka's runtime without the need to manage database storage. Changes to your data can be automatically replicated to multiple places, not only within a single service, but also across applications and even cloud providers. An SQL-like language lets you design read access that ensures the data is properly indexed for your application needs.

Integrations with message systems like Kafka are already built-in and the Akka SDK enables message consumers to listen to topics and queues.

== Prerequisites

The following are required to develop services with the Akka SDK:

include::ROOT:partial$local-dev-prerequisites.adoc[]
* https://docs.docker.com/get-started/get-docker/[Docker Engine, window="new"] {minimum_docker_version} or later

== Getting Started

Follow xref:java:author-your-first-service.adoc[] to implement your first service. If you prefer to first explore working example code, you can check out the xref:shopping-cart/quickstart.adoc[] or our other xref:samples.adoc[samples].

On the other hand, if you would rather spend some time exploring our documentation, here are some main features you will find in this section:

* xref:event-sourced-entities.adoc[Event Sourced Entities]
* xref:key-value-entities.adoc[Key Value Entities]
* xref:http-endpoints.adoc[HTTP Endpoints]
* xref:grpc-endpoints.adoc[gRPC Endpoints]
* xref:views.adoc[Views]
* xref:workflows.adoc[Workflows]
* xref:timed-actions.adoc[Timed Actions]
* xref:consuming-producing.adoc[Consuming and Producing]
