= Akka SDK

include::ROOT:partial$include.adoc[]

Building services with the Akka SDK leads you into embracing proven design patterns that enable your apps to remain responsive to change. It frees you from infrastructure concerns and lets you focus on the application logic.

With its few, concise components, the Akka SDK is easy to learn, and you can develop services in quick, iterative steps by running your code locally with full insight through Akka's console.

Akka services let you build REST endpoints with flexible access control and multiple ways to expose these endpoints to their consuming systems or applications. Akka is secure by default, and you explicitly express the desired access through code and configuration.

Akka encapsulates data together with the logic to access and modify it. The data itself is expressed in regular Java records (plain old Java objects). The same goes for the events that change the data, these are expressed in pure Java to reflect business events that lead to data updates. Akka enables you to build fully event-driven services by combining logic and data into one thing: entities.

Data and changes to it are managed by Akka's runtime without the need to manage database storage. Changes to your data can be automatically replicated to multiple places, not only within a single service, but also across applications and even cloud providers. An SQL-like language lets you design read access that ensures the data is properly indexed for your application needs.

Integrations with message systems like Kafka are already built-in and the Akka SDK enables message consumers to listen to topics and queues.

== Prerequisites

The following are required to develop services with the Akka SDK:

Java:: Java {java-version} or later.

Apache Maven:: https://maven.apache.org/[Apache Maven {tab-icon}, window="new"] is the recommended build tool with the Akka SDK.

== A simple service

:TODO: Graph view of the customer registry service with endpoints, entities and views.

This tiny service exposes its REST API (POST, PATCH, GET,...) through Endpoints.
The data and changes to it are defined as Java records describing the domain that are managed as an Entity.
To query the data, the service offers Views.

== Getting Started

Follow our xref:java:getting-started.adoc["Getting started with the Akka SDK"] guide to implement your first service. If you prefer to first explore working example code, you can check out the xref:samples:index.adoc[beginner samples].

On the other hand, if you would rather spend some time exploring our documentation, here are some main features you will find in this section:

* xref:http-endpoints.adoc[REST Endpoints]
* xref:key-value-entities.adoc[Key Value Entities]
* xref:event-sourced-entities.adoc[Event Sourced Entities]
* xref:views.adoc[Views]
* xref:consuming-producing.adoc[Consuming and Producing]
* xref:timed-actions.adoc[Timed Actions]
* xref:workflows.adoc[Workflows]
