= Run a service locally

Running a service locally is helpful to test and debug. The following sections provide commands for starting and stopping a single service locally.

== Prerequisites

In order to run your service locally, you'll need to have the following prerequisites:

 * JDK 21
 * Maven

== Starting your service

To start your service locally, run the following command from the root of your project:

--
[source, command line]
----
mvn compile exec:java
----
--

== Invoking your service

After you start the service it will accept invocations on `localhost:9000`. You can use cURL to invoke your service.

As an example, we will use the https://github.com/lightbend/akka-javasdk/tree/main/samples/event-sourced-customer-registry[`customer-registry`] sample.

=== Using cURL

Create a customer:

[.tabset]
Linux or macOS::
+
--
[source,command line]
----
curl -i localhost:9000/customer \
  --header "Content-Type: application/json" \
  -XPOST \
  --data '{"id": "one","email":"test@example.com","name":"Test Testsson","address":{"street":"Teststreet 25",
  "city":"Testcity"}}'
----
--
Windows 10+::
+
--
[source,command line]
----
curl -i localhost:9000/customer ^
  --header "Content-Type: application/json" ^
  -XPOST ^
  --data '{"id": "one","email":"test@example.com","name":"Test Testsson","address":{"street":"Teststreet 25",
  "city":"Testcity"}}'
----
--

Retrieve an existing customer:

--
[source,command line]
----
curl localhost:9000/customer/one
----
--

== Shutting down the service

Use `Ctrl+C` to shut down the service.

== Running service with persistence enabled

By default, when running locally, persistence is disabled. This means the Akka Runtime will use an in-memory datastore for the state of your services. This is useful for local development since it allows you to quickly start and stop your service without having to worry about cleaning the database.

However, if you want to run your service with persistence enabled to keep the data when restarting, you can configure
the service in `application.conf` with `akka.javasdk.dev-mode.persistence.enabled=true` or as a system property when
running starting the service locally `mvn compile exec:java -Dakka.javasdk.dev-mode.persistence.enabled=true`.

ifdef::todo[TODO: will only work once https://github.com/lightbend/kalix-runtime/issues/2758 is sorted]

== Running multiple services locally

A typical application is composed of one or more services deployed to the same Akka project. When deployed under the same project, two different services can make xref:component-and-service-calls.adoc[calls to each other] or xref:service-to-service.adoc[subscribe to each other's event streams] by simply using their logical names.

The same can be done on your local machine by configuring the services to run on different ports. The services
will discover each other by name and will be able to interact.

In this section, we will show you how to configure your local development environment to run two services and have them call each other.
For that we will use two of our existing samples: https://github.com/lightbend/akka-javasdk/tree/main/samples/spring-event-sourced-customer-registry[`customer-registry`] and https://github.com/lightbend/akka-javasdk/tree/main/samples/spring-event-sourced-customer-registry-subscriber[`customer-registry-subscriber`].

The *customer-registry* sample provides a service to register customers and the *customer-registry-subscriber* subscribes to an event stream produced by the *customer-registry* service, building a xref:views.adoc[View] from it.

=== Customer Registry Sample

The *customer-registry* service is left as is, to use the usual default port 9000.

=== Customer Registry Subscriber Sample

On the other hand, in the *customer-registry-subscriber* we will use port 9001 to avoid port conflicts with the
*customer-registry* service. This port is configured in `akka.javasdk.dev-mode.http-port` property in
`src/main/resources/application.conf` file.


[source,xml,indent=0]
----
include::java:example$event-sourced-customer-registry-subscriber/src/main/resources/application.conf[tag=custom-port]
----

With both services configured, we can start them independently by running `mvn compile exec:java` in two separate terminals.

From a third terminal, we can create a customer on *customer-registry* service.

[.tabset]
Linux or macOS::
+
--
[source,command line]
----
curl localhost:9000/customer \
  --header "Content-Type: application/json" \
  -XPOST \
  --data '{"id": "one","email":"test@example.com","name":"Test Testsson","address":{"street":"Teststreet 25",
  "city":"Testcity"}}'
----
--
Windows 10+::
+
--
[source,command line]
----
curl localhost:9000/customer ^
  --header "Content-Type: application/json" ^
  -XPOST ^
  --data '{"id": "one","email":"test@example.com","name":"Test Testsson","address":{"street":"Teststreet 25",
  "city":"Testcity"}}'
----
--

While watching the logs in *customer-registry-subscriber* service, we will see it receiving the customer created event. After that we can query its View.

--
[source,command line]
----
curl localhost:9001/customer/by_name/Test%20Testsson
----
--
