= Samples
include::ROOT:partial$include.adoc[]

[TIP]
====
*New to Akka? Start here:* 

xref:java:author-your-first-service.adoc[] to get a minimal "Hello World!" Akka service and run it locally.
====

Samples are available that demonstrate important patterns and abstractions. These can be cloned from their respective repositories. Please refer to the `README` file in each repository for setup and usage instructions.

[options="header", cols="3,2,1"]
|=======================
| Description | Source download | Level
| xref:java:shopping-cart/index.adoc[Build a shopping cart] | link:https://github.com/akka-samples/shopping-cart-quickstart[Github Repository] |Beginner
| A customer registry with query capabilities | link:../java/_attachments/customer-registry-quickstart.zip[customer-registry-quickstart.zip] |Intermediate
| A funds transfer workflow between two wallets | link:../java/_attachments/workflow-quickstart.zip[workflow-quickstart.zip] |Intermediate
| A user registration service implemented as a Choreography Saga | link:../java/_attachments/choreography-saga-quickstart.zip[choreography-saga-quickstart.zip] |Advanced
| Akka Chess: a complete, resilient, automatically scalable, event-sourced chess game | https://github.com/akka-samples/akka-chess[Github Repository] |Advanced
|=======================

[sidebar]
It is also possible to deploy a pre-built sample project in https://console.akka.io[the Akka console, window="new"], eliminating the need for local development.

== Maven archetype

To create the build structure of a new service you can use the Maven archetype. From a command window, in the parent directory of the new service, run the following:

[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--

The xref:java:author-your-first-service.adoc[] starts from the Maven archetype and lets you implement a very simple service.
