= Implementing Views

include::ROOT:partial$include.adoc[]

Views allow you to access multiple entities or retrieve entities by attributes other than their xref:reference:glossary.adoc#entity-id[entity id]. You can create Views for different access patterns, optimized by specific queries, or combine multiple queries into a single View.

Views can be defined from any of the following:

* xref:value-entity[Key Value Entity state changes]
* xref:event-sourced-entity[Event Sourced Entity events]
* xref:topic-view[Messages received from subscribing to topics on a broker]
* xref:consuming-producing.adoc#s2s-eventing[Events consumed from a different Akka service]

The remainder of this page describes:

* <<#results-projection>>
* <<#changing>>
* <<#query>>

IMPORTANT: Be aware that Views are not updated immediately when the Entity state changes. It is not instant but eventually all changes will become visible in the query results. View updates might also take more time during failure scenarios (e.g. network instability) than during normal operation.

[#_effect_api]
== View's Effect API

The View's Effect defines the operations to be performed when an event, a message or a state change is handled by a View.

A View Effect can either:

* update the view state
* delete the view state
* ignore the event or state change notification (and not update the view state)

See also xref:concepts:declarative-effects.adoc[Declarative Effects] for more information.

[#value-entity]
== Creating a View from a Key Value Entity

Consider an example of a Customer Registry service with a `Customer` Key Value Entity. When customer state changes, the entire state is emitted as a value change. Those value changes update any associated Views.
To create a View that lists customers by their name, <<_define_the_view, define the view>> for a service that selects customers by name and associates a table name with the View. The table is created and used to store the View.


This example assumes the following `Customer` exists:

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/domain/Customer.java[Customer.java]
----
include::example$key-value-customer-registry/src/main/java/customer/domain/Customer.java[tags=class]
----

As well as a Key Value Entity component `CustomerEntity.java` that will produce the state changes consumed by the View. You can consult xref:key-value-entities.adoc#entity-behavior[Key Value Entity] documentation on how to create such an entity if needed.


=== Define the View

You implement a View by extending `akka.javasdk.view.View` and subscribing to changes from an entity. You specify how to query it by providing one or more methods annotated with `@Query`, which can then be made accessible via an xref:java:http-endpoints.adoc[HTTP Endpoint].

[source,java]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomersByEmail.java[CustomersByEmail.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomersByEmail.java[tags=class]
----
<1> Define a component id for the view.
<2> Extend from `View`.
<3> Subscribe to updates from Key Value Entity `CustomerEntity`.
<4> Declare a `TableUpdater` of type `Customer` (entity's state type).
<5> Define the query, including a table name (i.e. `customers_by_email`) of our choice.
<6> Use method `queryResult()` to return the result of the query.


IMPORTANT: Assigning a component identifier (i.e. `@ComponentId`) to your View is mandatory, it must be unique, and it should be stable. This allows you to refactor the name of the class later on without the risk of losing the view. If you change this identifier later, Akka will not recognize this component as the same view and will create a brand-new view. For a view consuming from an Event Sourced Entity this becomes very resource consuming because it will reprocess all the events of that entity to rebuild it. While for a view built from a topic, you can lose all the previous events because, depending on the topic configuration, you may only process events from the current time forwards. Last but not least, it's also a problem for Key Value Entities because it will need to index them again when grouping them by some value.

=== Using a transformed model

Often, you will want to transform the entity model to which the view is subscribing into a different representation. To do that, let's have a look at the example in which we store a summary of the `Customer` used in the previous section instead of the original one:

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomersByName.java[CustomersByName.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomersByName.java[tag=row]
----

In this scenario, the view state should be of type `CustomerSummary` and you will need to handle and transform the incoming state changes into it, as shown below:

[source,java]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomersByName.java[CustomersByName.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomersByName.java[tags=class]
----
<1> Declares a `TableUpdater` of type `CustomerSummary`. This type represents each stored row.
<2> Implements a handler method `onUpdate` that receives the latest state of the entity `Customer` and returns an `Effect` with the updated row.
<3> The id of the entity that was updated is available through the update context as `eventSubject`.
<4> Defines the query.
<5> Uses the new type `CustomerSummary` to return the result of the query.



[#ve_delete]
=== Handling Key Value Entity deletes

The View state corresponding to an Entity is not automatically deleted when the Entity is deleted.

We can update our table updater with an additional handler marked with `@DeleteHandler`, to handle a Key Value Entity xref:key-value-entities.adoc#deleting-state[delete] operation.

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomerSummaryByName.java[CustomerSummaryByName.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomerSummaryByName.java[tag=delete]
----
<1> Note we are adding a new handler to the existing table updater.
<2> Marks the method as a delete handler.
<3> An effect to delete the view row `effects().deleteRow()`. It could also be an update of a special column, to mark the view row as deleted.

[#event-sourced-entity]
== Creating a View from an Event Sourced Entity

You can create a View from an Event Sourced Entity by using events that the Entity emits to build a state representation.

Using our Customer Registry service example, to create a View for querying customers by name,
you have to <<_define_the_view_to_consume_events, define the view to consume events>>.

This example assumes a Customer equal to the previous example and an Event Sourced Entity that uses this Customer. The Event Sourced Entity is in charge of producing the events that update the View. These events are defined as subtypes of the class `CustomerEvent` using a sealed interface:

[source,java]
.{sample-base-url}/event-sourced-customer-registry/src/main/java/customer/domain/CustomerEvent.java[CustomerEvent.java]
----
include::example$event-sourced-customer-registry/src/main/java/customer/domain/CustomerEvent.java[tags=class]
----
<1> Includes the logical type name using `@TypeName` annotation.

IMPORTANT: It's highly recommended to add a `@TypeName` to your persisted events. Akka needs to identify each event in order to deliver them to the right event handlers. If no logical type name is specified, Akka uses the FQCN, check xref:serialization.adoc#_type_name[type name] documentation for more details.


=== Define the View to consume events

Defining a view that consumes from an Event Sourced Entity is very similar to the one consuming a Key Value Entity. In this case, the handler method will be called for each event emitted by the Entity.

Every time an event is processed by the view, the state of the view can be updated. You can do this with the `updateRow` method, which is available through the `effects()` API. Below you can see how the View is updated:

[source,java]
.{sample-base-url}/event-sourced-customer-registry/src/main/java/customer/application/CustomerByNameView.java[CustomerByNameView.java]
----
include::example$event-sourced-customer-registry/src/main/java/customer/application/CustomerByNameView.java[tags=class]
----
<1> Defines a component id for the view.
<2> Declares a `TableUpdater` of type `CustomerRow`.
<3> Handles the super type `CustomerEvent` and defines the proper update row method for each subtype.


=== Ignoring events

You can ignore events by returning `Effect.ignore` for those you are not interested in. Using a `sealed interface` for the events is a good practice to ensure that all events types are handled.

[#es_delete]
=== Handling Event Sourced Entity deletes

The View row corresponding to an Entity is not automatically deleted when the Entity is deleted.

To delete from the View you can use the `deleteRow()` effect from an event transformation method, similarly to the example shown above for a Key Value Entity.

[#topic-view]
== Creating a View from a topic

The source of a View can be a topic. It works the same way as shown in <<event-sourced-entity>> or <<value-entity>>, but you define it with `@Consume.FromTopic` instead.

NOTE: For the messages to be correctly consumed in the view, there must be a `ce-subject` metadata associated with each message. This is required because for each message consumed from the topic there will be a corresponding view row. That view row is selected based on such `ce-subject`. See the example below for how to pass such metadata when producing to a topic with Akka SDK.

[source,java]
.{sample-base-url}/event-sourced-counter-brokers/src/main/java/counter/application/CounterJournalToTopicWithMetaConsumer.java[CounterJournalToTopicWithMetaConsumer.java]
----
include::example$event-sourced-counter-brokers/src/main/java/counter/application/CounterJournalToTopicWithMetaConsumer.java[tag=class]
----
<1> Uses `@Consume.FromTopic` annotation to set the target topic.
<2> Composes the `ce-subject` attribute from the entity's event subject.
<3> Returns a producing effect with the updated metadata together with the message payload.

[#results-projection]
== How to transform results

When creating a View, you can transform the results as a projection for constructing a new type instead of using a `SELECT *` statement.


=== Result projection

Instead of using `SELECT *` you can define which columns will be used in the response message. If you want to use a `CustomerSummary` used on the previous section, you will need to define your entity as this:

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomerSummaryByName.java[CustomerSummaryByName.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomerSummaryByName.java[tag=projection]
----
<1> Note the renaming from `customerId` as `id` on the query, as `id` and `name` match the record `CustomerSummary`.
<2> Returns the query result.

In a similar way, you can include values from the request in the response, for example `:requestId`:

[source,sql]
----
SELECT :requestId, customerId as id, name FROM customers
WHERE name = :customerName
----

=== Multiple results

Oftentimes a query might be designed to return multiple results. In this case, you can either:

* Wrap the results in a `Collection` field in the response type.
* Stream the results to the client.

==== Wrapping results in a Collection

To include the results in a `Collection` field in the response object, you can do as below:

[source,java]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomerList.java[CustomerList.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomerList.java[tag=class]
----

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomersResponseByName.java[CustomersResponseByName.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomersResponseByName.java[tag=class]
----
<1> Table updater type is the original `Customer` as shown at the beginning of this section.
<2> Note the use of `* AS customers` so records are matched to `customers` field in `CustomersList`.
<3> Return type of the query is `CustomersList`.


==== Streaming view updates

A query can provide a near real-time stream of results for the query, emitting new entries matching the query as they are added or updated in
the view.

This will first list the complete result for the query and then keep the response stream open, emitting new or updated
entries matching the query as they are added to the view. The stream does not complete until the client closes it.

To use streaming, modify the returned type to be `QueryStreamEffect` instead and use `queryStreamResult()` to return the stream.

NOTE: This is not intended as transport for xref:consuming-producing.adoc#s2s-eventing[service to service] propagation of updates, and it does not guarantee delivery. For such use cases you
should instead publish events to a topic, see xref:consuming-producing.adoc[]

[#changing]
== How to modify a View

Akka creates indexes for the View based on the queries. For example, the following query will result in a View with an index on the `name` column:

[source,sql,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name
----

You may realize after a deployment that you forgot adding some parameters to the query parameters that aren't exposed to the endpoint of the View. After adding these parameters the query is changed and therefore Akka will add indexes for these new columns. For example, changing the above query to filter by active users would mean a new index on the `is-active` column. This is handled automatically behind the scenes.

[source,sql,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name AND is-active = true
----


=== Incompatible changes

Some specific scenarios might require a complete rebuild of the View, for example:

* adding or removing tables for multi-table views;
* changing the data type of a column that is part of an index.

Such changes require you to define a new View. Akka will then rebuild it from the source event log or value changes.

TIP: You should be able to test if a change is compatible locally by running the service with xref:java:running-locally.adoc#_running_service_with_persistence_enabled[persistence mode enabled], producing some data, and then changing the View query and re-running the service. If the service boots up correctly and is able to serve the new query, the change is compatible.

Rebuilding a new View may take some time if there are many events that have to be processed. The recommended way when changing a View is multi-step, with two deployments:

. Define the new View with a new `@ComponentId`, and keep the old View intact.
. Deploy the new View, and let it rebuild. Verify that the new query works as expected. The old View can still be used.
. Remove the old View and redirect the endpoint calls to the new View.
. Deploy the second change.

The View definitions are stored and validated when a new version is deployed. There will be an error message if the changes are not compatible.

WARNING: Views from topics cannot be rebuilt from the source messages, because it might not be possible to consume all events from the topic again. The new View is built from new messages published to the topic.


[#query]
include::java:partial$query-syntax-reference.adoc[]

include::java:partial$query-syntax-advanced.adoc[]

== Testing the View

Testing Views is very similar to testing other xref:consuming-producing.adoc#_testkit_mocked_incoming_messages[subscription integrations].

For a View definition that subscribes to changes from the `customer` Key Value Entity.

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/main/java/customer/application/CustomersByCity.java[CustomersByCity.java]
----
include::example$key-value-customer-registry/src/main/java/customer/application/CustomersByCity.java[tag=view-test]
----

An integration test can be implemented as below.

[source,java,indent=0]
.{sample-base-url}/key-value-customer-registry/src/it/java/customer/application/CustomersByCityIntegrationTest.java[CustomersByCityIntegrationTest.java]
----
include::example$key-value-customer-registry/src/it/java/customer/application/CustomersByCityIntegrationTest.java[tag=view-test]
----
<1> Mocks incoming messages from the `customer` Key Value Entity.
<2> Gets an `IncomingMessages` from the `customer` Key Value Entity.
<3> Publishes test data.
<4> Queries the view and asserts the results.


== Exposing views directly

include::partial$component-endpoint.adoc[]

=== API

The view is exposed at a fixed path:

[source]
----
/akka/v1.0/view/<component id>/<method>
----

Taking the sample from the <<value-entity, first section>> as an example, that would be:

[source,shell]
----
curl localhost:9000/akka/v1.0/view/view_customers_by_email/getCustomer \
  --header "Content-Type: application/json" \
  -XPOST \
  --data '{"email":"test2@example.com"}'
----
