= Samples
include::ROOT:partial$include.adoc[]

[TIP]
====
*New to Akka? Start here:* 

xref:java:build-your-first-application.adoc[*Build a shopping cart*]

This sample is recommended for beginners and provides a foundational understanding of Akka. Start here before exploring other samples.
====

Other samples are available that demonstrate important patterns and abstractions. These can be downloaded as zip files. Please refer to the `README` file in each zip for setup and usage instructions.

[options="header", cols="4,2"]
|=======================
| Sample|Level
| link:../java/_attachments/customer-registry-quickstart.zip[Build a customer registry with query capabilities]|Intermediate
| link:../java/_attachments/workflow-quickstart.zip[Build a funds transfer workflow between two wallets]|Intermediate
| link:../java/_attachments/choreography-saga-quickstart.zip[Build a user registration service implemented as a Choreography Saga]|Advanced
|=======================

[sidebar]
It is also possible to deploy a pre-built sample project in https://console.akka.io[the Akka console], eliminating the need for local development.

== Maven archetype

To create the build structure of a new service you can use the Maven archetype. From a command window, in the parent directory of the new service, run the following:

[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--
