= Shopping Cart

include::ROOT:partial$include.adoc[]

:TODO: REVISE THIS CONTENT

Learn how to create a shopping cart, package it into a container, and run it on Akka.

include::partial$before-you-begin.adoc[]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Akka CLI:
`akka quickstart download shopping-cart`

. Skip to <<Package and deploy your service>>.
====

:TODO: include::java:partial$maven-archetype.adoc[]

== Shopping Cart Service

Through our "Shopping Cart" Event Sourced Entity we expect to manage our cart, adding and removing items as we please. Being event-sourced means it will represent changes to state as a series of domain events. So let’s have a look at what kind of model we expect to store and the events our entity might generate.

=== Define the domain model

First, define the domain class `ShoppingCart`, its domain events  in package `shoppingcart.domain` and some basic business logic.

[source,java,indent=0]
.src/main/java/shoppingcart/domain/ShoppingCart.java
----
include::java:example$shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[tag=all]
----

=== Define the entity

The Event Sourced Entity is defined in the `ShoppingCartEntity`.

Create a class named `ShoppingCartEntity` in package `shoppingcart.application`.

[source,java,indent=0]
.src/main/java/shoppingcart/application/ShoppingCartEntity.java
----
include::java:example$shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java[tag=all]
----

=== Define the external API

The `Shopping Cart` API is defined by the `ShoppingCartEndpoint`.

Create a class named `ShoppingCartEndpoint` in package `shoppingcart.api`.


[source,java,indent=0]
.src/main/java/shoppingcart/api/ShoppingCartEndpoint.java
----
include::java:example$shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java[tag=all]
----

include::partial$package-and-deploy.adoc[]


Items can be added to a shopping cart using the `/cart/\{cartId}/item` endpoint on the ShoppingCart service:

[source,command line]
----
curl -i -XPUT -H "Content-Type: application/json" localhost:8080/carts/123/item -d '
{"productId":"akka-tshirt", "name":"Akka Tshirt", "quantity": 10}'
----

The state of the cart can be retrieved with `/cart/\{cartId}`.

[source, command line]
----
curl localhost:8080/carts/123
----

And finally, you can check out the cart with `/cart/\{cartId}/checkout`.

[source, command line]
----
curl -i -XPOST localhost:8080/carts/123/checkout
----

include::partial$expose-service.adoc[]

== Next steps

* You can learn more about xref:java:event-sourced-entities.adoc[Event Sourced Entities].
