= akka services data

Manage the data of a service.

== Options

----
  -h, --help   help for data
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_services.html[akka services]	 - Manage and deploy services on Akka.
* link:akka_services_data_cancel-task.html[akka services data cancel-task]	 - Cancel a data operation task for a service
* link:akka_services_data_export.html[akka services data export]	 - Export the data of a service.
* link:akka_services_data_get-task.html[akka services data get-task]	 - Get a data operation task for a service
* link:akka_services_data_import.html[akka services data import]	 - Import data to a service.
* link:akka_services_data_list-tasks.html[akka services data list-tasks]	 - List data operation tasks for a service
* link:akka_services_data_watch-task.html[akka services data watch-task]	 - Watch a data operation task for a service

[discrete]

