= akka secrets

Manage secrets for an Akka project.

== Synopsis

The `akka secrets` command manages secrets for the currently configured project.
These secrets can then be referenced when configuring other properties (e.g.
JWTs) or can be made available to the service as environment variables.
See more details at https://doc.akka.io/operations/projects/secrets.html .

== Options

----
  -h, --help   help for secrets
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka.html[akka]	 - Akka control
* link:akka_secrets_create.html[akka secrets create]	 - Create or update a secret in the current project.
* link:akka_secrets_delete.html[akka secrets delete]	 - Delete a secret from the current project.
* link:akka_secrets_get.html[akka secrets get]	 - Get a secret and its keys in the current project.
* link:akka_secrets_list.html[akka secrets list]	 - List the secrets in the current project.

[discrete]

