= akka organizations

Manage your organizations on Akka

== Synopsis

The `akka organizations` commands manage the organizations in your Akka account.

== Options

----
  -h, --help   help for organizations
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka.html[akka]	 - Akka control
* link:akka_organizations_auth.html[akka organizations auth]	 - Manage authentication for your organization on Akka
* link:akka_organizations_get.html[akka organizations get]	 - Get organization information.
* link:akka_organizations_invitations.html[akka organizations invitations]	 - invitations
* link:akka_organizations_list.html[akka organizations list]	 - List all organizations of which the user is a member.
* link:akka_organizations_users.html[akka organizations users]	 - Manage organization users.

[discrete]

